/**
 * 
 */
package jsm.mdata.selenium.investing.screenshot;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @author Empleado
 *
 */
public class DriverControllerLST extends DriverControllerBase
{

	/**
	 * Logger
	 */
	private final static Logger LOGGER = LoggerFactory.getLogger(DriverControllerLST.class);

	/**
	 * URL Groups
	 */
	private final static List<URLGroup> LISTA_URL_GROUP = new ArrayList<URLGroup>();
	static
	{
		// --
		// -- ETFs Alemania
		// --
		// List<String> listaURL_01 = new ArrayList<String>();
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-emerging-markets?cid=45949");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-europe-energy?cid=45955");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-europe-healthcare?cid=45977");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-europe-industrials?cid=45982");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-europe-insurance?cid=45980");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-europe-utilities?cid=45993");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-japan---eur?cid=45983");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-world-energy---eur?cid=45995");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-etf-msci-world-x-emu?cid=45985");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-china-de");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-east-euro-x-russia-de");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-europe-banks-de");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-europe-materials?cid=46111");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-europe-telecom-ser.?cid=46135");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-india---eur-de");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-pacific-x-japan---eur?cid=46125");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-world-de");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-world-financials---eur");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-msci-world-x-europe---eur?cid=46114");
		// listaURL_01.add("https://es.investing.com/etfs/amundi-real-estate-reit-ieif?cid=46112");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-alpha-dividende-plus");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-dj-industrial-average");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-ftse-china-a50?cid=1024667");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-hscei");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-msci-emerging-markets-trn");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-msci-japan-trn");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-msci-pacific-x-japan-trn");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-msci-russia-30-cappedtr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-msci-world-trn");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-nyse-arca-gold-bugs");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-s-p-smit-40-trn?cid=1024623");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx600-auto.--parts-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx600-basic-res.-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx600-food--bev.-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx600-health-care-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx600-ind.-goods--ser.");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx600-travel--lei.-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx-euro-600-retail-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx-euro-600-telecom-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx-europe-600-banks-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx-europe-600-media-nr");
		// listaURL_01.add("https://es.investing.com/etfs/comstage-stoxx-europe-600-tech-nr");
		// listaURL_01.add("https://es.investing.com/etfs/cs-(ie)-on-msci-canada-de");
		// listaURL_01.add("https://es.investing.com/etfs/cs-(ie)-on-msci-pacific-x-japan-de");
		// listaURL_01.add("https://es.investing.com/etfs/cs-etf(ie)on-cs-gbl-altrn.engy");
		// listaURL_01.add("https://es.investing.com/etfs/cs-etf-(ie)-on-msci-japan?cid=45843");
		// listaURL_01.add("https://es.investing.com/etfs/cs-etf-(ie)-on-msci-russia?cid=45845");
		// listaURL_01.add("https://es.investing.com/etfs/db-ftse-nareit-dev.-euro-re-1c");
		// listaURL_01.add("https://es.investing.com/etfs/db-msci-russia-25-cap-uk?cid=46771");
		// listaURL_01.add("https://es.investing.com/etfs/db-stoxxeuro600-basic-res.");
		// listaURL_01.add("https://es.investing.com/etfs/db-stoxxeuro600-food--beverage");
		// listaURL_01.add("https://es.investing.com/etfs/db-stoxxeuro600-ind.-goods");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-csi-300-index?cid=46094");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-ftse-xinhua-china-25?cid=45808");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-harvest-csi300");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-msci-ac-world-index");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-msci-canada-trn-uk?cid=46540");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-msci-china-trn-uk?cid=46543");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-msci-china-trn-uk?cid=46543");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-msci-em-emea-trn");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-msci-em-trn-idx-etf?cid=45821");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-msci-india-trn-uk?cid=46725");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-msci-japantr---eur");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-msci-japan-trn-etf?cid=45809");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-msci-world-trn-uk?cid=46409");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-msci-wrd-hlth-care-de");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-portfolio-tr-index?cid=1056526");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-s-p-global-infr.-uk?cid=38694");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-s-p-select-frontier");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-stoxx-euro-600-banks");
		// listaURL_01.add("https://es.investing.com/etfs/db-x-trackers-stoxx-euro-600-tech");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrackers-stoxx-glbl-div-100?cid=46096");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-dr-1d");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-energy-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-finls-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-indust-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-mats-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-minvol-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-qlt-fct-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-util-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-world-val-fct-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/db-xtrack-msci-wrld-cons-disc-1c?cid=1024387");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-wrld-consstpl-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrack-msci-wrld-tlcom-srvc-dr-1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrck-msci-world-4c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrck-msci-world-mom-fact-dr1c");
		// listaURL_01.add("https://es.investing.com/etfs/dbxtrck-msci-wrld-infotech-dr-1c-mi?cid=1009153");
		// listaURL_01.add("https://es.investing.com/etfs/dj-stoxx600-health-care");
		// listaURL_01.add("https://es.investing.com/etfs/dj-stoxx600-telecommunications");
		// listaURL_01.add("https://es.investing.com/etfs/etflab-msci-china");
		// listaURL_01.add("https://es.investing.com/etfs/etflab-msci-emerging-markets");
		// listaURL_01.add("https://es.investing.com/etfs/etflab-msci-japan");
		// listaURL_01.add("https://es.investing.com/etfs/etflab-msci-japan-lc");
		// listaURL_01.add("https://es.investing.com/etfs/etflab-msci-japan-mc");
		// listaURL_01.add("https://es.investing.com/etfs/etfs-ise-cyber-sec-go-accum");
		// listaURL_01.add("https://es.investing.com/etfs/etfx-daxglobal-gold-mining-fund");
		// listaURL_01.add("https://es.investing.com/etfs/euro-stoxx-optimised-banks-source");
		// listaURL_01.add("https://es.investing.com/etfs/fundlogic-alter-plc-ms-scibeta-glbl");
		// listaURL_01.add("https://es.investing.com/etfs/hang-seng-h-share?cid=1010571");
		// listaURL_01.add("https://es.investing.com/etfs/hsbc-eco-scale-worldwide-eq-ucits");
		// listaURL_01.add("https://es.investing.com/etfs/hsbc-msci-japan-de");
		// listaURL_01.add("https://es.investing.com/etfs/hsbc-msci-pacific-x-japan-de");
		// listaURL_01.add("https://es.investing.com/etfs/hsbc-msci-world");
		// listaURL_01.add("https://es.investing.com/etfs/hsbc-multifactor-worldwide-eq-ucits");
		// listaURL_01.add("https://es.investing.com/etfs/icbc-crsuiss-wtre-sp-china-500-b-de");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-ageing-population-acc?cid=1037050");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-automation-robotics-acc?cid=1009408");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-core-msci-em-imi?cid=1024491");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-digitalisation-acc?cid=1080073");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-china-offshore-50---de");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-em-select-dividend-%C2%A3?cid=46600");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-global-sust-screened-uk?cid=38617");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-global-titans-50");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-industrial-average");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-auto-parts");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-banks");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-basicresources");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-financial-svs");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-food-beverage");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-health-care");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-insurance");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-stoxx600-media");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-dj-us-energy-sector-fund?cid=21520");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-edge-msci-world-mf-gbp?cid=994123");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-edge-msci-world-min-vol");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-edge-msci-wrld-multihdg-acc");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-eurostoxx-600-real-estate");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-eurostoxx-600-technology");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-eurostoxx-600-telecom--de");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-eurostoxx600-trvl---leis.");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-eurostoxx-600-utilities");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-euro-stoxx-banks---de");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-euro-stoxx-telecom---de");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-exponential-tech-mu");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-ftse-birc-50---ie?cid=38607");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-ftse-nareit-asia-fd?cid=38604");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-ftse-nareit-dev.-markets?cid=38605");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-ftse-nareit-us-prop-fd?cid=38606");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-ftse-xinhua-china25?cid=45780");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-global-clean-energy?cid=45836");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-hc-innov-acc-mi?cid=1009026");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-macquarie-global-inf.-100?cid=38611");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-ac-far-east-x-japan?cid=38609");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-china-a-ucits-usd?cid=994116");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-em-consumer-growth");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-emerging-market?cid=46607");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-emerging-mrkt---acc?cid=46604");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-em-minimum-volatility?cid=994135");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-em-smlcap-$?cid=46606");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-global-gold-miners-be");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-japan---acc?cid=46059");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-japan---ie?cid=45811");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-japan-mon.-euro-hed.?cid=46741");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-japan-small-cap");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-pacific-ex-japan-uk?cid=45777");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-world---acc?cid=45873");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-world---gbp?cid=38614");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-world-momentum-factor");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-world-mon.-hedged?cid=46487");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-wrld-quality-factor");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-wrld-size-factor");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-msci-wrld-value-factor");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-nareit-european-prop.-fund?cid=38612");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-s-p-comm.-prod.-oil-gas");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-s-p-commodity-prod.-gold");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-s-p-emerging-mkts-infr.?cid=46608");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-s-p-glbl-water?cid=46491");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-s-p-listed-private-eqty?cid=46492");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-stoxx600-ind.-goods--ser.");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-stoxx-euro-600-retail");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-stoxx-europe-600-chemicals");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-stoxx-global-sel-div.-100");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-sust-msci-em-sri");
		// listaURL_01.add("https://es.investing.com/etfs/ishares-v-msci-acwi?cid=46483");
		// listaURL_01.add("https://es.investing.com/etfs/ishrs-edge-msci-wrld-minvol-hdg-acc");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-china-enterprise-(hscei)?cid=45807");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-dj-industrial-average?cid=46142");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-japan-(topix)-daily-hedged-mi?cid=962222");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-japan---topix?cid=46011");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-ac-asia-pacific-x-japan?cid=45950");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-all-country-world-de");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-emerging-markets?cid=46020");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-europe-real-estate?cid=46182");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-india?cid=46155");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-usa-real-estate?cid=46188");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world?cid=46273");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-cons.-st.-tr?cid=45990");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-consumer-disc.-tr?cid=46122");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-energy-tr?cid=46033");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-financials-tr?cid=46006");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-health-care-tr?cid=46008");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-industrials-tr?cid=46010");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-info-tech-tr?cid=46225");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-materials-tr?cid=46025");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-real-estate?cid=46031");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-telecom-ser.-tr?cid=46041");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-msci-world-utilities-tr?cid=46272");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-new-energy?cid=46168");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-privex?cid=46192");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-russia---dj-russia-gdr?cid=46163");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-600-ind.-goods---ser.?cid=46153");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx600-per.--house.-goods?cid=46174");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxxeuro-600-auto.---parts?cid=46104");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxxeuro-600-food---bev.?cid=46167");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxxeuro-600-travel--lei.?cid=46175");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-banks?cid=46171");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-basic-res.?cid=46068");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-chemicals?cid=46117");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-health-care?cid=46172");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-insurance?cid=46176");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-media?cid=46181");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-retail?cid=46035");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-technology?cid=46023");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-telecom?cid=46040");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-utilities?cid=46024");
		// listaURL_01.add("https://es.investing.com/etfs/lyxor-world-water?cid=46017");
		// listaURL_01.add("https://es.investing.com/etfs/marketaccess-arca-gold-bugs-uk?cid=942310");
		// listaURL_01.add("https://es.investing.com/etfs/msci-emerging-mrktssource-de");
		// listaURL_01.add("https://es.investing.com/etfs/msci-japan-source?cid=45891");
		// listaURL_01.add("https://es.investing.com/etfs/msci-pacific-x-japan-trn-%C2%A3-uk?cid=46403");
		// listaURL_01.add("https://es.investing.com/etfs/msci-world-source?cid=46070");
		// listaURL_01.add("https://es.investing.com/etfs/ossiam-em-min-variance-nr-(eur)-de");
		// listaURL_01.add("https://es.investing.com/etfs/powershares-dynamic-europe-fund?cid=45898");
		// listaURL_01.add("https://es.investing.com/etfs/rbs-market-access-dax-global-birc");
		// listaURL_01.add("https://es.investing.com/etfs/rbs-market-access-daxglobal-russia");
		// listaURL_01.add("https://es.investing.com/etfs/robo-stox-global-robotics");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-acwi?cid=46046");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-acwi-imi-de");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-emerging-markets?cid=45850");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-em-smlcap?cid=45851");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-consumer-discr.?cid=46218");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-consumer-staples?cid=46219");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-energy?cid=46184");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-financials?cid=46223");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-health-care?cid=46222");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-industrials?cid=46217");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-info-tech?cid=46215");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-materials?cid=46216");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-telecom-services?cid=46220");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-europe-utilities?cid=46221");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-msci-world-small-cap?cid=1024392");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-s-p-emerging-mrktsdividend-uk?cid=45833");
		// listaURL_01.add("https://es.investing.com/etfs/spdr-s-p-global-dividend-aristocrat?cid=1024489");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx600-opt.-auto.--parts-source");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-opt.-banks-source-de");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx600-opt.-food--bev.-source");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx600-opt.-per.--house.-goods");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx600-opt.-travel--lei.-sou.");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-basic-res.");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-chemicals");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-financial-ser.");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-health-care");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-insurance");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-media-source");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-retail-source");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-tech-source");
		// listaURL_01.add("https://es.investing.com/etfs/stoxx-600-optimised-telecom-source");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-(irl)-dj-global-select-dividend?cid=949270");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-etf-msci-canada-de");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-etf-msci-emerging-markets-a");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-etf-msci-japan-a");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-etf-msci-pacific-x-japan-de");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-etf-msci-world-a");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-irl-plc-solactive-glbl-oil-adis?cid=1024391");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-irl-plc-sol-glbl-gold-min-adis?cid=1024390");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-msci-em-socially-resp-adis");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-msci-world-socially-resp.-a-de");
		// listaURL_01.add("https://es.investing.com/etfs/ubs-plc-msci-world-(usd)-a-de");
		// listaURL_01.add("https://es.investing.com/etfs/wisdomtree-em-equity-incacc");
		// listaURL_01.add("https://es.investing.com/etfs/wisdomtree-em-equity-income-de");
		// listaURL_01.add("https://es.investing.com/etfs/wisdomtree-em-smallcap-de");
		// LISTA_URL_GROUP.add(new URLGroup("GER", listaURL_01));
		// --
		// -- ETFs USA
		// --
		// List<String> listaURL_02 = new ArrayList<String>();
		// listaURL_02.add("https://es.investing.com/etfs/aam-sp-em-sector-high-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/advisorshares-madrona-intl");
		// listaURL_02.add("https://es.investing.com/etfs/advisorshrs-new-tech-media");
		// listaURL_02.add("https://es.investing.com/etfs/affinity-world-leaders-equity");
		// listaURL_02.add("https://es.investing.com/etfs/alpha-architect-value-mom-trend");
		// listaURL_02.add("https://es.investing.com/etfs/alphaclone-international");
		// listaURL_02.add("https://es.investing.com/etfs/alps-alerian-energy-infra");
		// listaURL_02.add("https://es.investing.com/etfs/alps-emerging-sector-dividend-dogs");
		// listaURL_02.add("https://es.investing.com/etfs/amplify-online-retail");
		// listaURL_02.add("https://es.investing.com/etfs/amplify-transform-data-sharing");
		// listaURL_02.add("https://es.investing.com/etfs/anfield-capital-divers-alter");
		// listaURL_02.add("https://es.investing.com/etfs/arrow-dogs-of-the-world");
		// listaURL_02.add("https://es.investing.com/etfs/barclays-bank-fi-enhanced-global");
		// listaURL_02.add("https://es.investing.com/etfs/barclays-bank-ipath-sp-mlp");
		// listaURL_02.add("https://es.investing.com/etfs/barclays-etn-plus-select-mlp");
		// listaURL_02.add("https://es.investing.com/etfs/barclays-women-in-leadership");
		// listaURL_02.add("https://es.investing.com/etfs/bernstein-global-research-fund");
		// listaURL_02.add("https://es.investing.com/etfs/beyond-bircs");
		// listaURL_02.add("https://es.investing.com/etfs/cambria-emerg-shareholder-yield");
		// listaURL_02.add("https://es.investing.com/etfs/claymore-mac-global-solar-energy-in");
		// listaURL_02.add("https://es.investing.com/etfs/columbia-sust-glbl-equity-inc");
		// listaURL_02.add("https://es.investing.com/etfs/columbia-sust-int-eqty-income");
		// listaURL_02.add("https://es.investing.com/etfs/credit-suisse-x-links-multi-asset");
		// listaURL_02.add("https://es.investing.com/etfs/csop-china-csi-300-a-h-dynamic");
		// listaURL_02.add("https://es.investing.com/etfs/csop-ftse-china-a50-us");
		// listaURL_02.add("https://es.investing.com/etfs/csop-msci-china-a-intl-hedged");
		// listaURL_02.add("https://es.investing.com/etfs/cwa-income");
		// listaURL_02.add("https://es.investing.com/etfs/davis-select-international");
		// listaURL_02.add("https://es.investing.com/etfs/davis-select-worldwide");
		// listaURL_02.add("https://es.investing.com/etfs/db-x-msci-eafe-currency-hedged-eq");
		// listaURL_02.add("https://es.investing.com/etfs/db-x-msci-em-currency-hedged-eq");
		// listaURL_02.add("https://es.investing.com/etfs/db-x-msci-japan-curr.-hedged-eq");
		// listaURL_02.add("https://es.investing.com/etfs/db-x-trackers-harvest-china");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-xtrackers-csi-300-china-a");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-x-trackers-ftse-developed");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-x-trackers-harvest-csi-500");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-xtrackers-msci-all-china");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-xtrackers-msci-eafe-high");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-x-trackers-msci-eafe-sc");
		// listaURL_02.add("https://es.investing.com/etfs/deutsche-x-track-hgh-yld-corp");
		// listaURL_02.add("https://es.investing.com/etfs/de-xtrack-ftse-emerging-comp-k");
		// listaURL_02.add("https://es.investing.com/etfs/direxion-daily-csi-300-china");
		// listaURL_02.add("https://es.investing.com/etfs/direxion-daily-csi-300-china-a-shar");
		// listaURL_02.add("https://es.investing.com/etfs/direxiondrobartfclintlautobull3shrs");
		// listaURL_02.add("https://es.investing.com/etfs/dow-jones-epac-select-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/dtec-alps-disruptive-tech");
		// listaURL_02.add("https://es.investing.com/etfs/dwcr-arrow-dwa-country-rotation");
		// listaURL_02.add("https://es.investing.com/etfs/eaton-vance-stock-nextshares");
		// listaURL_02.add("https://es.investing.com/etfs/egshares-em-core-ex-china");
		// listaURL_02.add("https://es.investing.com/etfs/egshares-emerging-markets-consumer");
		// listaURL_02.add("https://es.investing.com/etfs/egshares-india-consumer");
		// listaURL_02.add("https://es.investing.com/etfs/egshares-india-infrastructure");
		// listaURL_02.add("https://es.investing.com/etfs/egshares-india-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/egshares-low-volatility-em-div.");
		// listaURL_02.add("https://es.investing.com/etfs/emqq-em-internet-and-ecommerce");
		// listaURL_02.add("https://es.investing.com/etfs/etfis-virtus-wmc-global-factor-opp");
		// listaURL_02.add("https://es.investing.com/etfs/etracs-1xmon.-sh.-al.-mlp-infr.-tr");
		// listaURL_02.add("https://es.investing.com/etfs/etracs-alerian-mlp-infrastructure");
		// listaURL_02.add("https://es.investing.com/etfs/evolve-marijuana?cid=1075596");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-international-high-div");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-international-value-factor");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-energy-index");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-financials-index");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-healthcare-index");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-indust-index");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-info-tech");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-materials-index");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-telecom-svcs");
		// listaURL_02.add("https://es.investing.com/etfs/fidelity-msci-utilities-index");
		// listaURL_02.add("https://es.investing.com/etfs/fieldstone-merlin-dyn-large-cap");
		// listaURL_02.add("https://es.investing.com/etfs/fieldstone-uva-unconst-medterm");
		// listaURL_02.add("https://es.investing.com/etfs/financial-select-sector-spdr-fund");
		// listaURL_02.add("https://es.investing.com/etfs/firsttr.-nq-clean-edge-green-en.");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-alter-abso-rtrn-strtg");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-amex-biotech");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-bick");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-canada-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-capital-strength");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-china-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-developed-intl");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-dj-global-select-div.");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-dm-x-us-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-dm-x-us-smlcap-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-dorsey-wright-internati");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-emerging-mrkt-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-em-small-cap-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-energy-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-financials-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-health-care-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-heitman-glbl-prime-re");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-horizon-mng-vol-dm");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-industrials-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-indx-innvtv-trnsctnprc");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-inst-pref-secs-and-inc");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-international-ipo");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-ise-chindia");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-ise-glb-engnrg---const");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-ise-global-wind-energy");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-ise-water");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-japan-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-materials-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrustnasdaqartfclintlrobotics");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-nasdaq-global-auto");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-north-am.-energy-infr.");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-nq-100-technology");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-nq-100-x-tech-sector");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-nq-technology-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-riverfront-dynamic-dm");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-riverfront-dynamic-em");
		// listaURL_02.add("https://es.investing.com/etfs/first-trust-ssi-strtgconvert-sec");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-technology-alphadex");
		// listaURL_02.add("https://es.investing.com/etfs/firsttrust-utilities-alphadex-fund");
		// listaURL_02.add("https://es.investing.com/etfs/flexshares-core-select");
		// listaURL_02.add("https://es.investing.com/etfs/flexshares-currhdgd-morng-dm-exus");
		// listaURL_02.add("https://es.investing.com/etfs/flexshares-currhdgd-morningstar-em");
		// listaURL_02.add("https://es.investing.com/etfs/flexshares-real-assets-allocation");
		// listaURL_02.add("https://es.investing.com/etfs/flexshares-stoxx-gbl-brd-infrs");
		// listaURL_02.add("https://es.investing.com/etfs/flexshares-stoxx-global-esg-impact");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-ftse-china");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-liberty-interopp");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-liberty-invest-grade-corp");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-libertyq-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-libertyq-global-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-libertyq-global-equity");
		// listaURL_02.add("https://es.investing.com/etfs/franklin-libertyq-int-equity-hdg");
		// listaURL_02.add("https://es.investing.com/etfs/gavekal-knowledge-leaders-developed");
		// listaURL_02.add("https://es.investing.com/etfs/global-robotics-and-automation");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-auto-electric-vehicles");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-china-consumer");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-china-energy");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-china-financials");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-china-industrials");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-china-materials");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-copper-miners");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-fertilizers-potash");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-fintech-thematic");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-ftse-norway-30");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-gold-explorers");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-internet-things-them-usd");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-jpmorgan-efficiente");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-lithium");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-mlp");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-mlp---energy-infrs");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-msci-superdividend-eafe");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-nasdaq-china-technology");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-next-emer---frontier");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-robotics---ai-usd");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-social-media-index");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-superdividend");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-superdividend-alternatives");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-superdividend-emerging-mar");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-top-guru-holdings");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-uranium");
		// listaURL_02.add("https://es.investing.com/etfs/global-x-yieldco");
		// listaURL_02.add("https://es.investing.com/etfs/golden-dragon-halter-usx-china");
		// listaURL_02.add("https://es.investing.com/etfs/goldman-sachs-activebeta-em");
		// listaURL_02.add("https://es.investing.com/etfs/goldman-sachs-activebeta-inteqt");
		// listaURL_02.add("https://es.investing.com/etfs/graniteshares-gold-trust");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-birc");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-canada-energy-income");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-china-all-cap");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-china-smlcap");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-china-technology");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-defensive-equity");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-global-shipping");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-global-timber");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-intl-mul.-asset-income");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-s-p-global-div.-opp.");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-s-p-global-water");
		// listaURL_02.add("https://es.investing.com/etfs/guggenheim-sp-high-income-infrastr");
		// listaURL_02.add("https://es.investing.com/etfs/hartford-multi-lowvol-intern-equity");
		// listaURL_02.add("https://es.investing.com/etfs/holdrs-merrill-lynch-pharma.");
		// listaURL_02.add("https://es.investing.com/etfs/holdrs-merrill-lynch-semiconductor");
		// listaURL_02.add("https://es.investing.com/etfs/industrial-sector-spdr-trust");
		// listaURL_02.add("https://es.investing.com/etfs/innovation-shares-nextgen-protocol");
		// listaURL_02.add("https://es.investing.com/etfs/innovation-shares-nextgen-vhclstch");
		// listaURL_02.add("https://es.investing.com/etfs/innovator-ibd-50");
		// listaURL_02.add("https://es.investing.com/etfs/inspire-global-hope");
		// listaURL_02.add("https://es.investing.com/etfs/invesco-s-p-intl-dev-low-vol.");
		// listaURL_02.add("https://es.investing.com/etfs/ipath-msci-india-index-etn");
		// listaURL_02.add("https://es.investing.com/etfs/iq-50-percent-hedged-ftse-intl");
		// listaURL_02.add("https://es.investing.com/etfs/iq-arb-global-resources-etf");
		// listaURL_02.add("https://es.investing.com/etfs/iq-arb-merger-arbitrage");
		// listaURL_02.add("https://es.investing.com/etfs/iq-canada-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/iq-global-agribusiness-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/ise-cloud-computing");
		// listaURL_02.add("https://es.investing.com/etfs/ise-global-copper");
		// listaURL_02.add("https://es.investing.com/etfs/ise-global-platinum");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-adapt-cur-hdg-msci-eafe");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-core-msci-eafe");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-core-msci-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-core-msci-intern-dev-market");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-core-msci-total-intl-stock");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-currency-hdg-msci-acwi");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-currency-hdg-msci-eafe");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-currency-hdg-msci-em");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-currency-hedged-msci-acwi");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-currency-hedged-msci-eafe");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-aerospace---defense");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-basic-materials-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-broker-dealers-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-consumer");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-consumer-goods-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-financial-sector");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-financial-services");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-health-care-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-health-care-providers");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-home-construction");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-industrial-sector");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-insurance");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-medical-devices-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-pharmaceutical-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-regional-banks-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-technology");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-telecommunications");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-djsu-utilities");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-dj-transport-average-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-dj-us-energy-sector-fund");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-edge-msci-international-siz");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-edge-msci-min-vol-eafe-cur");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-edge-msci-min-vol-em-cur-hd");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-edge-msci-multifactor-emerg");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-emerging-markets-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-exponential-tech-mu?cid=1043100");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-factorselect-msci-global");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-factorselect-msci-int");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-factorselect-msci-intl");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-ft-dev.-smlcap-x-north-am.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-ftse-xinhua-china-25");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-goldman-sachs-network");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-goldman-sachs-software");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-goldman-sachs-technology");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-ibonds-dec-2026-term-corp");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-int-div-grwth");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-acwi-index-fund");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-acwi-low-carbon-target");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-acwi-x-us");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-all-country-min.-vol.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-argentina-glbl-exp");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-birc");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-canada");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-china");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-china-a");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-china-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-denmark-cap-inv.-mrkt");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-eafe-esg-optimized");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-eafe-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-eafe-min-volatility");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-eafe-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-em-esg-optimized");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-em-ex-china");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-emg-markets");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-em-min-volatility");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-finland-cap-inv.-mrkt");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-global-energy-prod.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-global-gold-miners-be?cid=44703");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-global-impact");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-growth");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-india");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-india-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-international-develope");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-intl-dev-quality");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-intl-dev-value");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-japan");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci---kokusai");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-norway-cap-inv.-mrkt");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-russia-capped-index");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-sweden");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-value");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-msci-world");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-phlx-sox-semiconductor");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-developed-x-us-prop.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p---global-100");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-clean-energy");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-con.-stap.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-cons.discr.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-energy");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-financial");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-healthcare");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-industrials");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-infrastructure");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-materials");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-technology");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-telecom.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-timber---for.");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-global-utilities");
		// listaURL_02.add("https://es.investing.com/etfs/ishares-s-p-intl-preferred-stock");
		// listaURL_02.add("https://es.investing.com/etfs/janus-obesity");
		// listaURL_02.add("https://es.investing.com/etfs/janus-organics");
		// listaURL_02.add("https://es.investing.com/etfs/john-hancock-multifactor-dm");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-disciplined-high-yield");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-diverrtrn-intcurrhdgd");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-diversi");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-diversified-alternative");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-diversified-return-emergin");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-diversified-return-global");
		// listaURL_02.add("https://es.investing.com/etfs/jpmorgan-managed-futures-strategy");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-bosera-msci-china-a");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-csi-china-5-y-plan");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-csi-china-internet");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-elctrcvhcls-fturemblty");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-em-consumer-tech");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-ftse-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-msci-china-hlth-cr-indx");
		// listaURL_02.add("https://es.investing.com/etfs/kraneshares-msci-one-belt-one-road");
		// listaURL_02.add("https://es.investing.com/etfs/lattice-developed-markets-ex-us-str");
		// listaURL_02.add("https://es.investing.com/etfs/lattice-emerging-markets-strategy");
		// listaURL_02.add("https://es.investing.com/etfs/lattice-global-small-cap-strategy");
		// listaURL_02.add("https://es.investing.com/etfs/legg-mason-dm-exus-diversifcore");
		// listaURL_02.add("https://es.investing.com/etfs/legg-mason-em-diversified-core-etf");
		// listaURL_02.add("https://es.investing.com/etfs/legg-mason-em-lowvol-hidiv");
		// listaURL_02.add("https://es.investing.com/etfs/legg-mason-intl-lowvol-hidi");
		// listaURL_02.add("https://es.investing.com/etfs/marketv.-rare-earth-strat.-metals");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-agribusiness");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-biotech");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-china");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-chinaamc-sme-chinext");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-coal");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-gaming");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-global-alt.-energy");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-global-spin-off");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-gold-miners");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-hard-assets-prod.");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-india-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-junior-gold-miners");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-morningstar-intl-moa");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-nuclear-energy");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-oil-refiners");
		// listaURL_02.add("https://es.investing.com/etfs/market-vectors-retail");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-russia-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-tr-russia");
		// listaURL_02.add("https://es.investing.com/etfs/marketvectors-unconv.-oil---gas");
		// listaURL_02.add("https://es.investing.com/etfs/momentumshares-intl-quant-mom");
		// listaURL_02.add("https://es.investing.com/etfs/morningstar-dm-x-us-factor-tilt");
		// listaURL_02.add("https://es.investing.com/etfs/morningstar-em-factor-tilt");
		// listaURL_02.add("https://es.investing.com/etfs/morningstar-g.-upstream-nat.-res.");
		// listaURL_02.add("https://es.investing.com/etfs/msci-emerging-markets-smlcp-fund");
		// listaURL_02.add("https://es.investing.com/etfs/msci-europe-financials-secto");
		// listaURL_02.add("https://es.investing.com/etfs/msci-frontier-100");
		// listaURL_02.add("https://es.investing.com/etfs/msci-global-agri.-producers-fund");
		// listaURL_02.add("https://es.investing.com/etfs/msci-global-metals-mining-prod.");
		// listaURL_02.add("https://es.investing.com/etfs/msci-global-silver-miners-fund");
		// listaURL_02.add("https://es.investing.com/etfs/msci-japan-small-cap");
		// listaURL_02.add("https://es.investing.com/etfs/nationwide-risk-based-intl");
		// listaURL_02.add("https://es.investing.com/etfs/natixis-seeyond-intl-minvol");
		// listaURL_02.add("https://es.investing.com/etfs/nq-clean-edge-smart-grid-infras.");
		// listaURL_02.add("https://es.investing.com/etfs/oppenheimer-global-esg-revenue");
		// listaURL_02.add("https://es.investing.com/etfs/oshares-ftse-rusl-intl-qual-div");
		// listaURL_02.add("https://es.investing.com/etfs/pimco-rafi-dyn-multifactor-em");
		// listaURL_02.add("https://es.investing.com/etfs/pimco-rafi-dyn-multifactor-intl");
		// listaURL_02.add("https://es.investing.com/etfs/portfolioplus-developed-markets");
		// listaURL_02.add("https://es.investing.com/etfs/portfolioplus-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/powers.-wilderhill-prog.-energy");
		// listaURL_02.add("https://es.investing.com/etfs/powersh.-dynamic-biotech---genome");
		// listaURL_02.add("https://es.investing.com/etfs/powersh.-dynamic-food---beverage");
		// listaURL_02.add("https://es.investing.com/etfs/powersh.-dynamic-pharmaceuticals");
		// listaURL_02.add("https://es.investing.com/etfs/powersh.-global-gold---pr.-metals");
		// listaURL_02.add("https://es.investing.com/etfs/powersh.-intl-dividend-achievers");
		// listaURL_02.add("https://es.investing.com/etfs/powersh.-rafi-asia-pacific-x-japan");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-aerospace---defense");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-bldrs-em-50-adr");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-cleantech-portfolio");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dwa-momlowvol-rotation");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-dev-int-opp");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-energy-e-p");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-leisure---ent.");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-media");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-retail");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-semiconductors");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-dynamic-software");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-financial-preferred");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-ft-rafi-emerging-mrkt");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-ftse-int-lowbeta-eqlwgt");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-ftse-rafi-dm-x-us");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-global-agriculture");
		// listaURL_02.add("https://es.investing.com/etfs/powershares---global-clean-energy");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-global-em-infr.");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-global-water");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-india-portfolio");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-international-buyback-a");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-purebeta-ftse-dev");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-purebeta-ftse-em");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-sp500-val-with-mom-port");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-s-p-em-low-volatility");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-s-p-smallcap-energy");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-s-p-smallcap-info-tech");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-s-p-smallcap-materials");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-sp-smallcap-qual-port");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-varrate-invest-grade");
		// listaURL_02.add("https://es.investing.com/etfs/powershares-water-resource-port");
		// listaURL_02.add("https://es.investing.com/etfs/powershr-dwa-em-mom");
		// listaURL_02.add("https://es.investing.com/etfs/powershrs-sp-intl-dvl-hidiv-lowvol");
		// listaURL_02.add("https://es.investing.com/etfs/powersh-s-p-smallcap-financials");
		// listaURL_02.add("https://es.investing.com/etfs/powersh-s-p-smallcap-healthcare");
		// listaURL_02.add("https://es.investing.com/etfs/powersh-s-p-small-cap-utilities");
		// listaURL_02.add("https://es.investing.com/etfs/powersh-wilderhill-clean-energy");
		// listaURL_02.add("https://es.investing.com/etfs/premise-cap-frnt-advant-divrs-tact");
		// listaURL_02.add("https://es.investing.com/etfs/principal-active-global-div-inc");
		// listaURL_02.add("https://es.investing.com/etfs/principal-millennials");
		// listaURL_02.add("https://es.investing.com/etfs/proshares-dj-brookfield-global-infr");
		// listaURL_02.add("https://es.investing.com/etfs/proshares-msci-eafe-dividend-grower");
		// listaURL_02.add("https://es.investing.com/etfs/proshares-msci-em-div-gr");
		// listaURL_02.add("https://es.investing.com/etfs/pshares-bldrs-dm-100-adr");
		// listaURL_02.add("https://es.investing.com/etfs/pshares-ftse-rafi-dm-x-us-sml-mid");
		// listaURL_02.add("https://es.investing.com/etfs/purefunds-drone-economy-strategy");
		// listaURL_02.add("https://es.investing.com/etfs/purefunds-ise-cyber-security");
		// listaURL_02.add("https://es.investing.com/etfs/purefunds-video-game-tech");
		// listaURL_02.add("https://es.investing.com/etfs/reality-shares-nasdaq-nexgen-econ");
		// listaURL_02.add("https://es.investing.com/etfs/recon-capital-nasdaq-100-covered");
		// listaURL_02.add("https://es.investing.com/etfs/revenueshares-financials-sector");
		// listaURL_02.add("https://es.investing.com/etfs/rex-bkcm");
		// listaURL_02.add("https://es.investing.com/etfs/riverfront-dynamic-core-income");
		// listaURL_02.add("https://es.investing.com/etfs/riverfront-dynamic-unconstr-inc");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-msci-em-eq-weight");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-energy");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-financial");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-health-care");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-industrials");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-materials");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-technology");
		// listaURL_02.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-utilities");
		// listaURL_02.add("https://es.investing.com/etfs/saba-interest-rate-hedged-cef");
		// listaURL_02.add("https://es.investing.com/etfs/salix-pharmaceuticals-ltd.");
		// listaURL_02.add("https://es.investing.com/etfs/schwab-1000");
		// listaURL_02.add("https://es.investing.com/etfs/schwab-emerging-markets-equity");
		// listaURL_02.add("https://es.investing.com/etfs/schwab-international-equity");
		// listaURL_02.add("https://es.investing.com/etfs/schwab-intl-small-cap-equity");
		// listaURL_02.add("https://es.investing.com/etfs/silver-miners");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-consumer-discr.-select-sector");
		// listaURL_02.add("https://es.investing.com/etfs/spdr---consumer-staples");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-dj-global-titans");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-dj-wilshire-intl-real-estate");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-energy-select-sector-fund");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-ftse-macquarie-gi-100");
		// listaURL_02.add("https://es.investing.com/etfs/spdr---health-care");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-kbw-capital-markets");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-kbw-insurance");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-kbw-regional-banking");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-materials-select-sector-etf");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-acwi-ex-us");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-acwi-imi");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-acwi-low-carbon-target");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-china-a-shares-imi");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-eafe-fossil-fuel-rsrvfree");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-eafe-quality-mix");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-emerging-markets-quality");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-em-fossil-fuel-free");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-msci-world-quality-mix");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-ms-technology");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-select-sector---technology");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-select-sector---utilities");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-aerospace---defense");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-biotech");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-china");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-emerging-markets-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-emerging-markets-smallcap");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-global-natural-resources");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-health-care-equipment");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-health-care-services");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-homebuilders");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-intl-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-intl-smallcap");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-metals---mining");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-pharmaceuticals");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-retail");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-semiconductor");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-software---services");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-telecom");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-transportation");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-s-p-world-ex-us");
		// listaURL_02.add("https://es.investing.com/etfs/spdr-wilshire-global-real-estate");
		// listaURL_02.add("https://es.investing.com/etfs/s-p-emerging-markets-high-beta");
		// listaURL_02.add("https://es.investing.com/etfs/s-p-emerging-mrkt-infrastructure");
		// listaURL_02.add("https://es.investing.com/etfs/s-p-india-nifty-fifty");
		// listaURL_02.add("https://es.investing.com/etfs/spirited-funds-etfmg-whiskey");
		// listaURL_02.add("https://es.investing.com/etfs/the-3d-printing");
		// listaURL_02.add("https://es.investing.com/etfs/the-wear");
		// listaURL_02.add("https://es.investing.com/etfs/ubs-ag-fi-enhanced-glbl-hgh-yld");
		// listaURL_02.add("https://es.investing.com/etfs/usaa-msci-em-value-mom-blend");
		// listaURL_02.add("https://es.investing.com/etfs/usaa-msci-intl-value-mom-blend");
		// listaURL_02.add("https://es.investing.com/etfs/vaneck-vectors-generic-drugs");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-consumer-discretion");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-consumer-staples");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-energy");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-europe-pacific");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-financials");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-ftse-all-wld-x-us-smcp");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-ftse-all-world?cid=1065342");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-ftse-all-world-x-us");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-ftse-emerging-markets");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-global-ex-su-real-estate");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-health-care");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-industrials");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-information-tech");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-int-div-appreciation");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-int-high-div-yld");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-materials");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-telecom");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-total-intl-stock");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-total-world-stock-index");
		// listaURL_02.add("https://es.investing.com/etfs/vanguard-utilities");
		// listaURL_02.add("https://es.investing.com/etfs/victory-cemp-international-high-div");
		// listaURL_02.add("https://es.investing.com/etfs/victory-cemp-international-vol");
		// listaURL_02.add("https://es.investing.com/etfs/victoryshares-em-hidiv-vol-wtd");
		// listaURL_02.add("https://es.investing.com/etfs/vident-international-equity");
		// listaURL_02.add("https://es.investing.com/etfs/vident-international-equity?cid=1072337");
		// listaURL_02.add("https://es.investing.com/etfs/virtus-glovista-em");
		// listaURL_02.add("https://es.investing.com/etfs/wbi-tactical-rotation-shares");
		// listaURL_02.add("https://es.investing.com/etfs/wcm-bny-mellon-focused-growth-adr");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-asia-pacific-x-japan");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-china-div-ex-fincls");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-defa-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-defa-high-yielding-eq");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-dividend-x-financials");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-dyn-currhgd-intl");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-dyn-curr-hgd-intl-div-gr");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-em-consumer-growth");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-em-dividend-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-eme-income-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-emerging-mrkt-smallcap");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-em-ex-state-owned-ent");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-glbl-hgd-smallcap-div");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-global-smallcap-div");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-icbccs-sp-china-500");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-india-earnings-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-dividend-top-100");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-hdg-quality-div");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-hedged-equity-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-largecap-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-midcap-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-quality-div-gr");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-intl-smallcap-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-japan-smallcap-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-japan-total-dividend");
		// listaURL_02.add("https://es.investing.com/etfs/wisdomtree-world-ex-su-growth-fund");
		// listaURL_02.add("https://es.investing.com/etfs/wsdmtree-dyncurr-hgd-intl-smllcap");
		// listaURL_02.add("https://es.investing.com/etfs/xtrackers-msci-all-world");
		// listaURL_02.add("https://es.investing.com/etfs/xtrackers-msci-all-world-high-div");
		// LISTA_URL_GROUP.add(new URLGroup("USA", listaURL_02));
		// --
		// -- ETFs HEALTHCARE
		// --
		// List<String> listaURL_03 = new ArrayList<String>();
		// listaURL_03.add("https://es.investing.com/etfs/amundi-etf-msci-europe-healthcare?cid=45977");
		// listaURL_03.add("https://es.investing.com/etfs/comstage-stoxx600-health-care-nr");
		// listaURL_03.add("https://es.investing.com/etfs/db-x-trackers-msci-wrd-hlth-care-de");
		// listaURL_03.add("https://es.investing.com/etfs/dj-stoxx600-health-care");
		// listaURL_03.add("https://es.investing.com/etfs/fidelity-msci-healthcare-index");
		// listaURL_03.add("https://es.investing.com/etfs/firsttrust-health-care-alphadex");
		// listaURL_03.add("https://es.investing.com/etfs/rydex-s-p-equal-weight-health-care");
		// listaURL_03.add("https://es.investing.com/etfs/spdr---health-care");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-edge-msci-mf-healthcare");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-s-p-global-healthcare");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-hc-innov-acc-mi?cid=1009026");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-s-p-500-usd-health-care");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-dj-stoxx600-health-care");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-djsu-health-care-index");
		// listaURL_03.add("https://es.investing.com/etfs/ishares-djsu-health-care-providers");
		// listaURL_03.add("https://es.investing.com/etfs/john-hancock-multifactor-health");
		// listaURL_03.add("https://es.investing.com/etfs/lyxor-msci-world-health-care-tr?cid=46008");
		// listaURL_03.add("https://es.investing.com/etfs/lyxor-stoxx-europe-600-health-care?cid=46172");
		// listaURL_03.add("https://es.investing.com/etfs/powershares-dwa-healthcare-o");
		// listaURL_03.add("https://es.investing.com/etfs/powersh-s-p-smallcap-healthcare");
		// listaURL_03.add("https://es.investing.com/etfs/principal-healthcare-innovators");
		// listaURL_03.add("https://es.investing.com/etfs/stoxx-600-optimised-health-care");
		// listaURL_03.add("https://es.investing.com/etfs/spdr-msci-europe-health-care?cid=46222");
		// listaURL_03.add("https://es.investing.com/etfs/spdr-s-p-health-care-equipment");
		// listaURL_03.add("https://es.investing.com/etfs/spdr-s-p-health-care-services");
		// listaURL_03.add("https://es.investing.com/etfs/vanguard-health-care");
		// LISTA_URL_GROUP.add(new URLGroup("HEALTHCARE", listaURL_03));
		// --
		// -- ETFs BIOTECH
		// --
		// List<String> listaURL_04 = new ArrayList<String>();
		// listaURL_04.add("https://es.investing.com/etfs/bioshares-biotechnology-clinical");
		// listaURL_04.add("https://es.investing.com/etfs/bioshares-biotechnology-products");
		// listaURL_04.add("https://es.investing.com/etfs/firsttrust-amex-biotech");
		// listaURL_04.add("https://es.investing.com/etfs/powersh.-dynamic-biotech---genome");
		// listaURL_04.add("https://es.investing.com/etfs/spdr-s-p-biotech");
		// listaURL_04.add("https://es.investing.com/etfs/market-vectors-biotech");
		// LISTA_URL_GROUP.add(new URLGroup("BIOTECH", listaURL_04));
		// --
		// -- ETFs PHARMA
		// --
		// List<String> listaURL_05 = new ArrayList<String>();
		// listaURL_05.add("https://es.investing.com/etfs/ishares-djsu-pharmaceutical-index");
		// listaURL_05.add("https://es.investing.com/etfs/powersh.-dynamic-pharmaceuticals");
		// listaURL_05.add("https://es.investing.com/etfs/spdr-s-p-pharmaceuticals");
		// listaURL_05.add("https://es.investing.com/etfs/holdrs-merrill-lynch-pharma.");
		// LISTA_URL_GROUP.add(new URLGroup("PHARMA", listaURL_05));
		// --
		// -- ETFs MEDICAL
		// --
		// List<String> listaURL_06 = new ArrayList<String>();
		// listaURL_06.add("https://es.investing.com/etfs/alps-medical-breakthroughs");
		// listaURL_06.add("https://es.investing.com/etfs/ishares-djsu-medical-devices-index");
		// LISTA_URL_GROUP.add(new URLGroup("MEDICAL", listaURL_06));
		// --
		// -- ETFs ROBOTICS
		// --
		// List<String> listaURL_07 = new ArrayList<String>();
		// listaURL_07.add("https://es.investing.com/etfs/global-x-robotics---ai-usd");
		// listaURL_07.add("https://es.investing.com/etfs/ishares-automation-robotics-acc?cid=1009408");
		// listaURL_07.add("https://es.investing.com/etfs/robo-stox-global-robotics");
		// LISTA_URL_GROUP.add(new URLGroup("ROBOTICS", listaURL_07));
		// --
		// -- ETFs CHINA
		// --
		// List<String> listaURL_08 = new ArrayList<String>();
		// listaURL_08.add("https://es.investing.com/etfs/db-xtrackers-msci-china-trn-uk?cid=46543");
		// listaURL_08.add("https://es.investing.com/etfs/etflab-msci-china");
		// listaURL_08.add("https://es.investing.com/etfs/ishares-dj-china-offshore-50---de");
		// LISTA_URL_GROUP.add(new URLGroup("CHINA", listaURL_08));
		// --
		// -- ACCIONES CON DIVIDENDO
		// --
		List<String> listaURL_09 = new ArrayList<String>();
		listaURL_09.add("https://es.investing.com/equities/dominion-res");
		listaURL_09.add("https://es.investing.com/equities/united-utilities");
		listaURL_09.add("https://es.investing.com/equities/aena-aeropuertos-sa");
		listaURL_09.add("https://es.investing.com/equities/fortis-inc");
		listaURL_09.add("https://es.investing.com/equities/bp");
		listaURL_09.add("https://es.investing.com/equities/genuine-parts-co");
		listaURL_09.add("https://es.investing.com/equities/dover-corp");
		listaURL_09.add("https://es.investing.com/equities/procter-gamble");
		listaURL_09.add("https://es.investing.com/equities/emerson-elec");
		listaURL_09.add("https://es.investing.com/equities/3m-co");
		listaURL_09.add("https://es.investing.com/equities/johnson-johnson");
		listaURL_09.add("https://es.investing.com/equities/coca-cola-co");
		listaURL_09.add("https://es.investing.com/equities/lowes-companies");
		listaURL_09.add("https://es.investing.com/equities/colgate-palmo");
		listaURL_09.add("https://es.investing.com/equities/hormel-foods-corp");
		listaURL_09.add("https://es.investing.com/equities/target");
		listaURL_09.add("https://es.investing.com/equities/stanley-works");
		listaURL_09.add("https://es.investing.com/equities/altria-group");
		listaURL_09.add("https://es.investing.com/equities/w-w-grainger-inc");
		listaURL_09.add("https://es.investing.com/equities/leggett---platt");
		listaURL_09.add("https://es.investing.com/equities/becton-dickinsn");
		listaURL_09.add("https://es.investing.com/equities/pepsico");
		listaURL_09.add("https://es.investing.com/equities/kimberly-clark");
		listaURL_09.add("https://es.investing.com/equities/helmerich---payne");
		listaURL_09.add("https://es.investing.com/equities/vf-corp");
		listaURL_09.add("https://es.investing.com/equities/wal-mart-stores");
		listaURL_09.add("https://es.investing.com/equities/cocnsol-edison");
		listaURL_09.add("https://es.investing.com/equities/archer-daniels-mid");
		listaURL_09.add("https://es.investing.com/equities/illinois-tool-wk-r");
		listaURL_09.add("https://es.investing.com/equities/auto-data-process");
		listaURL_09.add("https://es.investing.com/equities/walgreen-co");
		listaURL_09.add("https://es.investing.com/equities/mcdonalds");
		listaURL_09.add("https://es.investing.com/equities/clorox-co");
		listaURL_09.add("https://es.investing.com/equities/medtronic");
		listaURL_09.add("https://es.investing.com/equities/franklin-res");
		listaURL_09.add("https://es.investing.com/equities/eaton-vance");
		listaURL_09.add("https://es.investing.com/equities/exxon-mobil");
		listaURL_09.add("https://es.investing.com/equities/aflac-inc");
		listaURL_09.add("https://es.investing.com/equities/air-prods---chem");
		listaURL_09.add("https://es.investing.com/equities/brown-forman-b");
		listaURL_09.add("https://es.investing.com/equities/at-t");
		listaURL_09.add("https://es.investing.com/equities/t-rowe-price-gp");
		listaURL_09.add("https://es.investing.com/equities/mccormick---co");
		listaURL_09.add("https://es.investing.com/equities/chevron");
		listaURL_09.add("https://es.investing.com/equities/roche-holding-ltd");
		listaURL_09.add("https://es.investing.com/equities/pz-cussons");
		listaURL_09.add("https://es.investing.com/equities/diageo");
		listaURL_09.add("https://es.investing.com/equities/general-dynam");
		listaURL_09.add("https://es.investing.com/equities/meredith-corp");
		listaURL_09.add("https://es.investing.com/equities/caterpillar");
		listaURL_09.add("https://es.investing.com/equities/realty-income");
		listaURL_09.add("https://es.investing.com/equities/aqua-america-inc.");
		listaURL_09.add("https://es.investing.com/equities/croda-international");
		listaURL_09.add("https://es.investing.com/equities/wpp");
		listaURL_09.add("https://es.investing.com/equities/united-tech");
		listaURL_09.add("https://es.investing.com/equities/nextera-energy-inc");
		listaURL_09.add("https://es.investing.com/equities/rpc-group");
		listaURL_09.add("https://es.investing.com/equities/cardinal-health");
		listaURL_09.add("https://es.investing.com/equities/ibm");
		listaURL_09.add("https://es.investing.com/equities/canadian-national-railway");
		listaURL_09.add("https://es.investing.com/equities/enbridge-inc.");
		listaURL_09.add("https://es.investing.com/equities/vodafone");
		listaURL_09.add("https://es.investing.com/equities/tjx-co-inc");
		listaURL_09.add("https://es.investing.com/equities/church---dwight");
		listaURL_09.add("https://es.investing.com/equities/nestle-ag");
		listaURL_09.add("https://es.investing.com/equities/novartis");
		listaURL_09.add("https://es.investing.com/equities/w-p-carey-inc");
		listaURL_09.add("https://es.investing.com/equities/imperial-tobacco");
		listaURL_09.add("https://es.investing.com/equities/jm-smucker-co");
		listaURL_09.add("https://es.investing.com/equities/sanofi");
		listaURL_09.add("https://es.investing.com/equities/red-electrica");
		listaURL_09.add("https://es.investing.com/equities/henkel-ag---co.-st");
		listaURL_09.add("https://es.investing.com/equities/muench.-rueck");
		listaURL_09.add("https://es.investing.com/equities/l-oreal");
		listaURL_09.add("https://es.investing.com/equities/danone");
		listaURL_09.add("https://es.investing.com/equities/southern-co");
		listaURL_09.add("https://es.investing.com/equities/flowers-foods");
		listaURL_09.add("https://es.investing.com/equities/british-american-tobacco");
		listaURL_09.add("https://es.investing.com/equities/siemens");
		listaURL_09.add("https://es.investing.com/equities/scottish---southern-energy");
		listaURL_09.add("https://es.investing.com/equities/cracker-barrelold-country");
		listaURL_09.add("https://es.investing.com/equities/nike");
		listaURL_09.add("https://es.investing.com/equities/tiffany---co");
		listaURL_09.add("https://es.investing.com/equities/microsoft-corp");
		listaURL_09.add("https://es.investing.com/equities/enagas");
		listaURL_09.add("https://es.investing.com/equities/suncor-energy-inc.");
		listaURL_09.add("https://es.investing.com/equities/novo-nordisk");
		listaURL_09.add("https://es.investing.com/equities/omega-healthcare");
		listaURL_09.add("https://es.investing.com/equities/qualcomm-inc");
		listaURL_09.add("https://es.investing.com/equities/hasbro-inc");
		listaURL_09.add("https://es.investing.com/equities/lockheed-martin");
		listaURL_09.add("https://es.investing.com/equities/edison-intl");
		listaURL_09.add("https://es.investing.com/equities/digital-realty-trust-inc");
		listaURL_09.add("https://es.investing.com/equities/kellogg-co.");
		listaURL_09.add("https://es.investing.com/equities/bayer-ag");
		listaURL_09.add("https://es.investing.com/equities/ameriprise-fincl");
		listaURL_09.add("https://es.investing.com/equities/texas-instru");
		listaURL_09.add("https://es.investing.com/equities/general-mills");
		listaURL_09.add("https://es.investing.com/equities/verizon-communications");
		listaURL_09.add("https://es.investing.com/equities/duke-energy");
		listaURL_09.add("https://es.investing.com/equities/air-liquide");
		listaURL_09.add("https://es.investing.com/equities/cummins-inc");
		listaURL_09.add("https://es.investing.com/equities/union-pacific");
		listaURL_09.add("https://es.investing.com/equities/unilever");
		listaURL_09.add("https://es.investing.com/equities/assoc.br.foods");
		listaURL_09.add("https://es.investing.com/equities/sap-ag");
		listaURL_09.add("https://es.investing.com/equities/comcast-corp-new");
		listaURL_09.add("https://es.investing.com/equities/brookfield-infrastructure-partners");
		listaURL_09.add("https://es.investing.com/equities/american-water-works-inc");
		listaURL_09.add("https://es.investing.com/equities/ahold-kon");
		listaURL_09.add("https://es.investing.com/equities/standard-life");
		listaURL_09.add("https://es.investing.com/equities/inditex");
		listaURL_09.add("https://es.investing.com/equities/philip-morris-intl");
		listaURL_09.add("https://es.investing.com/equities/visa-inc");
		listaURL_09.add("https://es.investing.com/equities/simon-prop-grp");
		listaURL_09.add("https://es.investing.com/equities/bristol-myer-squiib");
		listaURL_09.add("https://es.investing.com/equities/michelin");
		listaURL_09.add("https://es.investing.com/equities/allianz-ag");
		listaURL_09.add("https://es.investing.com/equities/axa");
		listaURL_09.add("https://es.investing.com/equities/bce");
		listaURL_09.add("https://es.investing.com/equities/blackrock,-inc.-c");
		listaURL_09.add("https://es.investing.com/equities/suez-environnement-s.a.");
		listaURL_09.add("https://es.investing.com/equities/deutsche-post");
		listaURL_09.add("https://es.investing.com/equities/pernod-ricard");
		listaURL_09.add("https://es.investing.com/equities/eaton");
		listaURL_09.add("https://es.investing.com/equities/united-parcel");
		listaURL_09.add("https://es.investing.com/equities/home-depot");
		listaURL_09.add("https://es.investing.com/equities/brookfield-renewable-partners-lp");
		listaURL_09.add("https://es.investing.com/equities/pfizer");
		listaURL_09.add("https://es.investing.com/equities/basf-ag");
		listaURL_09.add("https://es.investing.com/equities/corning-inc");
		listaURL_09.add("https://es.investing.com/equities/wells-fargo");
		listaURL_09.add("https://es.investing.com/equities/amgen-inc");
		listaURL_09.add("https://es.investing.com/equities/valero-energy");
		listaURL_09.add("https://es.investing.com/equities/cisco-sys-inc");
		listaURL_09.add("https://es.investing.com/equities/main-street-capital-corp");
		listaURL_09.add("https://es.investing.com/equities/avago-technologies");
		listaURL_09.add("https://es.investing.com/equities/disney");
		listaURL_09.add("https://es.investing.com/equities/paychex-inc");
		listaURL_09.add("https://es.investing.com/equities/ventas-inc");
		listaURL_09.add("https://es.investing.com/equities/adidas-salomon");
		listaURL_09.add("https://es.investing.com/equities/l.v.m.h.");
		listaURL_09.add("https://es.investing.com/equities/hershey-co");
		listaURL_09.add("https://es.investing.com/equities/starbucks-corp");
		listaURL_09.add("https://es.investing.com/equities/bt-group");
		listaURL_09.add("https://es.investing.com/equities/bay-mot-werke");
		listaURL_09.add("https://es.investing.com/equities/uniball");
		listaURL_09.add("https://es.investing.com/equities/renault");
		listaURL_09.add("https://es.investing.com/equities/legal---general");
		listaURL_09.add("https://es.investing.com/equities/scotiabank");
		listaURL_09.add("https://es.investing.com/equities/viscofan-sa");
		listaURL_09.add("https://es.investing.com/equities/whitbread");
		listaURL_09.add("https://es.investing.com/equities/gas-natural-sdg");
		listaURL_09.add("https://es.investing.com/equities/boeing-co");
		listaURL_09.add("https://es.investing.com/equities/royal-bank-of-canada-rbc");
		listaURL_09.add("https://es.investing.com/equities/amadeus");
		listaURL_09.add("https://es.investing.com/equities/toronto-dominion-bank");
		listaURL_09.add("https://es.investing.com/equities/us-bancorp");
		listaURL_09.add("https://es.investing.com/equities/linde");
		listaURL_09.add("https://es.investing.com/equities/burberry");
		listaURL_09.add("https://es.investing.com/equities/apple-computer-inc");
		listaURL_09.add("https://es.investing.com/equities/mastercard-cl-a");
		listaURL_09.add("https://es.investing.com/equities/brookfield-asset-management");
		listaURL_09.add("https://es.investing.com/equities/aegon");
		listaURL_09.add("https://es.investing.com/equities/abbvie-inc");
		listaURL_09.add("https://es.investing.com/equities/dominos-pizza");
		listaURL_09.add("https://es.investing.com/equities/metlife-inc");
		listaURL_09.add("https://es.investing.com/equities/veolia-environ");
		listaURL_09.add("https://es.investing.com/equities/american-express");
		listaURL_09.add("https://es.investing.com/equities/mondelez-international-inc");
		listaURL_09.add("https://es.investing.com/equities/iberdrola");
		listaURL_09.add("https://es.investing.com/equities/johnson-controls");
		listaURL_09.add("https://es.investing.com/equities/tyson-foods");
		listaURL_09.add("https://es.investing.com/equities/british-land");
		listaURL_09.add("https://es.investing.com/equities/kraft-foods-inc");
		listaURL_09.add("https://es.investing.com/equities/abbott-laboratories");
		listaURL_09.add("https://es.investing.com/equities/gilead-sciences-inc");
		listaURL_09.add("https://es.investing.com/equities/intel-corp");
		listaURL_09.add("https://es.investing.com/equities/playtech-limited");
		listaURL_09.add("https://es.investing.com/equities/zon-optimus-sa");
		listaURL_09.add("https://es.investing.com/equities/britvic");
		listaURL_09.add("https://es.investing.com/equities/bank-of-america");
		listaURL_09.add("https://es.investing.com/equities/restaurant-brands-intrnational");
		listaURL_09.add("https://es.investing.com/equities/aviva");
		listaURL_09.add("https://es.investing.com/equities/royal-mail");
		listaURL_09.add("https://es.investing.com/equities/atlantia");
		listaURL_09.add("https://es.investing.com/equities/repsol-ypf");
		listaURL_09.add("https://es.investing.com/equities/banco-santander");
		listaURL_09.add("https://es.investing.com/equities/ubs-group");
		listaURL_09.add("https://es.investing.com/equities/reckitt-benckiser");
		listaURL_09.add("https://es.investing.com/equities/acs-cons-y-serv");
		listaURL_09.add("https://es.investing.com/equities/rio-tinto");
		listaURL_09.add("https://es.investing.com/equities/daimler");
		listaURL_09.add("https://es.investing.com/equities/tate---lyle");
		listaURL_09.add("https://es.investing.com/equities/deere---co");
		listaURL_09.add("https://es.investing.com/equities/bhp-billiton");
		listaURL_09.add("https://es.investing.com/equities/heineken-nv");
		listaURL_09.add("https://es.investing.com/equities/kinder-morgan");
		listaURL_09.add("https://es.investing.com/equities/grupo-ferrovial");
		listaURL_09.add("https://es.investing.com/equities/telefonica");
		listaURL_09.add("https://es.investing.com/equities/caixabank-sa");
		listaURL_09.add("https://es.investing.com/equities/bbva");
		listaURL_09.add("https://es.investing.com/equities/royal-dutch-shell-a-plc");
		listaURL_09.add("https://es.investing.com/equities/mapfre");
		listaURL_09.add("https://es.investing.com/equities/bolsas-y-mer-esp");
		listaURL_09.add("https://es.investing.com/equities/limited-brands");
		listaURL_09.add("https://es.investing.com/equities/national-grid");
		listaURL_09.add("https://es.investing.com/equities/cvs-corp");
		listaURL_09.add("https://es.investing.com/equities/ebro-foods");
		listaURL_09.add("https://es.investing.com/equities/gdf-suez");
		listaURL_09.add("https://es.investing.com/equities/glaxosmithkline");
		listaURL_09.add("https://es.investing.com/equities/schnitzer-steel");
		listaURL_09.add("https://es.investing.com/equities/hanesbrands");
		listaURL_09.add("https://es.investing.com/equities/hennes---mauritz-ab");
		listaURL_09.add("https://es.investing.com/equities/compass-minerals-intl-inc");
		listaURL_09.add("https://es.investing.com/equities/general-electric");
		listaURL_09.add("https://es.investing.com/equities/health-care-reit");
		listaURL_09.add("https://es.investing.com/equities/anheuser-busch-inbev");
		LISTA_URL_GROUP.add(new URLGroup("DIVIDENDO", listaURL_09));
	}

	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		try
		{
			run();
		}
		catch (Exception e)
		{
			LOGGER.error("ERROR", e);
		}
		finally
		{
			LOGGER.info("FINALIZADO");
		}
	}

	/**
	 * @throws Exception
	 */
	private static void run() throws Exception
	{
		LOGGER.info("Suprimiendo ficheros temporales antiguos");
		FileUtils.cleanDirectory(new File(DOWNLOAD_PATH));

		LOGGER.info("Iniciando driver");
		System.setProperty(WEB_DRIVER_PROPERTY, WEB_DRIVER_EXE);
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--start-maximized");
		WebDriver driver = new ChromeDriver(options);

		LOGGER.info("Cargando URL inicial para introducir datos proxy");
		driver.get("https://es.investing.com/");
		new WebDriverWait(driver, 30).until(ExpectedConditions.visibilityOfElementLocated(By.className("disclaimer")));

		LOGGER.info("Iniciando proceso");
		for (URLGroup urlGroup : LISTA_URL_GROUP)
		{
			String downloadFolder = urlGroup.getDownloadFolder();
			LOGGER.info("Procesando grupo [" + downloadFolder + "]");
			List<String> listaURL = urlGroup.getListaURL();
			int urlsIdx = 0;
			while (urlsIdx < listaURL.size())
			{
				try
				{
					String hrefElemento = listaURL.get(urlsIdx);
					procesarElemento(driver, hrefElemento, DOWNLOAD_PATH + "\\" + downloadFolder + "\\" + TF_MENSUAL, TF_MENSUAL);
					// procesarElemento(driver, hrefElemento, DOWNLOAD_PATH + "\\" + downloadFolder + "\\" + TF_SEMANAL, TF_SEMANAL);
					// procesarElemento(driver, hrefElemento, DOWNLOAD_PATH + "\\" + downloadFolder + "\\" + TF_DIARIO, TF_DIARIO);
					urlsIdx++;
				}
				catch (Exception e)
				{
					LOGGER.error("Se ha producido un error", e);
					gestionError(driver);
				}
			}
		}

	}

}
