
-- (CASE WHEN 1=2 THEN NULL ELSE 2 END) AS XXX

SELECT TOTALES.PRODUCTO_ID, TOTALES.NOMBRE, TOTALES.TITULOS_COMPRADOS, TOTALES.PRECIO_TITULOS_COMPRADOS, TOTALES.TITULOS_VENDIDOS, TOTALES.PRECIO_TITULOS_VENDIDOS, (TOTALES.TITULOS_COMPRADOS - TOTALES.TITULOS_VENDIDOS) AS TITULOS_ACTUALES, PRECIOS.VALOR_TITULO FROM (
	SELECT COMPRAS.PRODUCTO_ID, COMPRAS.NOMBRE, COMPRAS.TITULOS_COMPRADOS, COMPRAS.PRECIO_TITULOS_COMPRADOS, VENTAS.TITULOS_VENDIDOS, VENTAS.PRECIO_TITULOS_VENDIDOS FROM (
		SELECT PRODUCTO_ID, NOMBRE, SUM(NUMERO_TITULOS) AS TITULOS_COMPRADOS, SUM((NUMERO_TITULOS * PRECIO_TITULO) + COMISION) AS PRECIO_TITULOS_COMPRADOS FROM VW01_MOVIMIENTO_PRODUCTO WHERE COMPRA_VENTA = 'Compra' GROUP BY PRODUCTO_ID, NOMBRE
	) COMPRAS
	LEFT OUTER JOIN (
		SELECT PRODUCTO_ID, NOMBRE, SUM(NUMERO_TITULOS) AS TITULOS_VENDIDOS, SUM((NUMERO_TITULOS * PRECIO_TITULO) + COMISION) AS PRECIO_TITULOS_VENDIDOS FROM VW01_MOVIMIENTO_PRODUCTO WHERE COMPRA_VENTA = 'Venta' GROUP BY PRODUCTO_ID, NOMBRE
	) VENTAS
	ON COMPRAS.PRODUCTO_ID = VENTAS.PRODUCTO_ID AND COMPRAS.NOMBRE = VENTAS.NOMBRE
) TOTALES
INNER JOIN TB02_PRECIOS PRECIOS 
ON TOTALES.PRODUCTO_ID = PRECIOS.PRODUCTO_ID;




SELECT PRODUCTO_ID, NOMBRE, TITULOS_COMPRADOS, PRECIO_TITULOS_COMPRADOS, TITULOS_VENDIDOS, PRECIO_TITULOS_VENDIDOS, TITULOS_ACTUALES, VALOR_TITULO, (TITULOS_ACTUALES * VALOR_TITULO) AS VALOR_MERCADO FROM (
	SELECT TOTALES.PRODUCTO_ID, TOTALES.NOMBRE, TOTALES.TITULOS_COMPRADOS, TOTALES.PRECIO_TITULOS_COMPRADOS, TOTALES.TITULOS_VENDIDOS, TOTALES.PRECIO_TITULOS_VENDIDOS, (TOTALES.TITULOS_COMPRADOS - TOTALES.TITULOS_VENDIDOS) AS TITULOS_ACTUALES, PRECIOS.VALOR_TITULO FROM (
		SELECT COMPRAS.PRODUCTO_ID, COMPRAS.NOMBRE, COMPRAS.TITULOS_COMPRADOS, COMPRAS.PRECIO_TITULOS_COMPRADOS, VENTAS.TITULOS_VENDIDOS, VENTAS.PRECIO_TITULOS_VENDIDOS FROM (
			SELECT PRODUCTO_ID, NOMBRE, SUM(NUMERO_TITULOS) AS TITULOS_COMPRADOS, SUM((NUMERO_TITULOS * PRECIO_TITULO) + COMISION) AS PRECIO_TITULOS_COMPRADOS FROM VW01_MOVIMIENTO_PRODUCTO WHERE COMPRA_VENTA = 'Compra' GROUP BY PRODUCTO_ID, NOMBRE
		) COMPRAS
		LEFT OUTER JOIN (
			SELECT PRODUCTO_ID, NOMBRE, SUM(NUMERO_TITULOS) AS TITULOS_VENDIDOS, SUM((NUMERO_TITULOS * PRECIO_TITULO) + COMISION) AS PRECIO_TITULOS_VENDIDOS FROM VW01_MOVIMIENTO_PRODUCTO WHERE COMPRA_VENTA = 'Venta' GROUP BY PRODUCTO_ID, NOMBRE
		) VENTAS
		ON COMPRAS.PRODUCTO_ID = VENTAS.PRODUCTO_ID AND COMPRAS.NOMBRE = VENTAS.NOMBRE
	) TOTALES
	INNER JOIN TB02_PRECIOS PRECIOS 
	ON TOTALES.PRODUCTO_ID = PRECIOS.PRODUCTO_ID
) MERCADO;

