SELECT 
	PRODUCTO_ID, 
	NOMBRE, 
	TITULOS_COMPRADOS, 
	PRECIO_TITULOS_COMPRADOS, 
	TITULOS_VENDIDOS, 
	PRECIO_TITULOS_VENDIDOS, 
	TITULOS_ACTUALES, 
	VALOR_TITULO, 
	CAST((TITULOS_ACTUALES * VALOR_TITULO) AS DECIMAL(31, 4)) AS VALOR_MERCADO 
FROM (
	SELECT 
		TOTALES.PRODUCTO_ID, 
		TOTALES.NOMBRE, 
		TOTALES.TITULOS_COMPRADOS, 
		TOTALES.PRECIO_TITULOS_COMPRADOS, 
		TOTALES.TITULOS_VENDIDOS, 
		TOTALES.PRECIO_TITULOS_VENDIDOS, 
		CAST((TOTALES.TITULOS_COMPRADOS - TOTALES.TITULOS_VENDIDOS) AS DECIMAL(31, 4)) AS TITULOS_ACTUALES, 
		PRECIOS.VALOR_TITULO 
	FROM (
		SELECT 
			COMPRAS.PRODUCTO_ID, 
			COMPRAS.NOMBRE, 
			COMPRAS.TITULOS_COMPRADOS, 
			COMPRAS.PRECIO_TITULOS_COMPRADOS, 
			(CASE WHEN VENTAS.TITULOS_VENDIDOS IS NULL THEN CAST(0 AS DECIMAL(31, 4)) ELSE VENTAS.TITULOS_VENDIDOS END) AS TITULOS_VENDIDOS,
			(CASE WHEN VENTAS.PRECIO_TITULOS_VENDIDOS IS NULL THEN CAST(0 AS DECIMAL(31, 4)) ELSE VENTAS.PRECIO_TITULOS_VENDIDOS END) AS PRECIO_TITULOS_VENDIDOS
		FROM (
			SELECT 
				PRODUCTO_ID, NOMBRE, 
				CAST(SUM(NUMERO_TITULOS) AS DECIMAL(31, 4)) AS TITULOS_COMPRADOS, 
				CAST(SUM((NUMERO_TITULOS * PRECIO_TITULO) + COMISION) AS DECIMAL(31, 4)) AS PRECIO_TITULOS_COMPRADOS 
			FROM VW01_MOVIMIENTO_PRODUCTO 
			WHERE COMPRA_VENTA = 'Compra' 
			GROUP BY PRODUCTO_ID, NOMBRE
		) 
		COMPRAS
		LEFT OUTER JOIN (
			SELECT 
				PRODUCTO_ID, 
				NOMBRE, 
				CAST(SUM(NUMERO_TITULOS) AS DECIMAL(31, 4)) AS TITULOS_VENDIDOS, 
				CAST(SUM((NUMERO_TITULOS * PRECIO_TITULO) + COMISION) AS DECIMAL(31, 4)) AS PRECIO_TITULOS_VENDIDOS 
			FROM VW01_MOVIMIENTO_PRODUCTO 
			WHERE COMPRA_VENTA = 'Venta' 
			GROUP BY PRODUCTO_ID, NOMBRE
		) 
		VENTAS
		ON COMPRAS.PRODUCTO_ID = VENTAS.PRODUCTO_ID AND COMPRAS.NOMBRE = VENTAS.NOMBRE
	) 
	TOTALES
	INNER JOIN TB02_PRECIOS PRECIOS ON TOTALES.PRODUCTO_ID = PRECIOS.PRODUCTO_ID
)
VALOR_MERCADO;