--
--
--
-- connect 'jdbc:derby:C:\\_JSM\\SeguimientoCartera\\03_Fuentes\\markets_data\\SeguimientoCartera\\derby\\seguimiento_cartera;create=true';
-- connect 'jdbc:derby:C:\\_JSM\\SeguimientoCartera\\03_Fuentes\\markets_data\\SeguimientoCartera\\derby\\seguimiento_cartera';
-- run 'C:\_JSM\SeguimientoCartera\03_Fuentes\markets_data\SeguimientoCartera\sql\seguimiento_cartera.sql';
--
--
--
AUTOCOMMIT OFF;
--
--
--
DROP TABLE SCRAP_PRECIOS;
DROP TABLE MASTER_MOVIMIENTOS;
DROP TABLE MASTER_PRODUCTOS;
DROP TABLE MASTER_PROVEEDOR;
DROP TABLE MASTER_INSTRUMENTO;
DROP TABLE MASTER_TIPO_ACTIVO;
DROP TABLE MASTER_SUBTIPO_ACTIVO;
DROP TABLE MASTER_MONEDA;
DROP TABLE MASTER_USO_INGRESOS;
DROP TABLE MASTER_COMPRA_VENTA;
DROP TABLE MASTER_COMERCIALIZADOR;
DROP TABLE MASTER_MERCADO;
--
--
--
CREATE TABLE MASTER_PROVEEDOR
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_PROVEEDOR ADD CONSTRAINT MASTER_PROVEEDOR_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_PROVEEDOR ADD CONSTRAINT MASTER_PROVEEDOR_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_INSTRUMENTO
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_INSTRUMENTO ADD CONSTRAINT MASTER_INSTRUMENTO_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_INSTRUMENTO ADD CONSTRAINT MASTER_INSTRUMENTO_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_TIPO_ACTIVO
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_TIPO_ACTIVO ADD CONSTRAINT MASTER_TIPO_ACTIVO_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_TIPO_ACTIVO ADD CONSTRAINT MASTER_TIPO_ACTIVO_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_SUBTIPO_ACTIVO
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_SUBTIPO_ACTIVO ADD CONSTRAINT MASTER_SUBTIPO_ACTIVO_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_SUBTIPO_ACTIVO ADD CONSTRAINT MASTER_SUBTIPO_ACTIVO_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_MONEDA
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_MONEDA ADD CONSTRAINT MASTER_MONEDA_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_MONEDA ADD CONSTRAINT MASTER_MONEDA_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_USO_INGRESOS
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_USO_INGRESOS ADD CONSTRAINT MASTER_USO_INGRESOS_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_USO_INGRESOS ADD CONSTRAINT MASTER_USO_INGRESOS_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_COMPRA_VENTA
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(25) NOT NULL
);
ALTER TABLE MASTER_COMPRA_VENTA ADD CONSTRAINT MASTER_COMPRA_VENTA_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_COMPRA_VENTA ADD CONSTRAINT MASTER_COMPRA_VENTA_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_COMERCIALIZADOR
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_COMERCIALIZADOR ADD CONSTRAINT MASTER_COMERCIALIZADOR_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_COMERCIALIZADOR ADD CONSTRAINT MASTER_COMERCIALIZADOR_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_MERCADO
(
	CLAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VALOR VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_MERCADO ADD CONSTRAINT MASTER_MERCADO_VALOR_PK Primary Key (VALOR);
ALTER TABLE MASTER_MERCADO ADD CONSTRAINT MASTER_MERCADO_CLAVE_UNQ Unique (CLAVE);
--
--
--
CREATE TABLE MASTER_PRODUCTOS
(
	IDENTIFICADOR VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	PROVEEDOR VARCHAR(50) NOT NULL,
	INSTRUMENTO VARCHAR(50) NOT NULL,
	TIPO_ACTIVO VARCHAR(50) NOT NULL,
	SUBTIPO_ACTIVO VARCHAR(50) NOT NULL,
	MONEDA VARCHAR(50) NOT NULL,
	USO_INGRESOS VARCHAR(50) NOT NULL,
	URL_SCRAPING VARCHAR(200) NOT NULL
);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_IDENTIFICADOR_PK Primary Key (IDENTIFICADOR);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_NOMBRE_UNQ Unique (NOMBRE);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_PROVEEDOR_FK Foreign Key (PROVEEDOR) REFERENCES MASTER_PROVEEDOR (VALOR);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_INSTRUMENTO_FK Foreign Key (INSTRUMENTO) REFERENCES MASTER_INSTRUMENTO (VALOR);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_TIPO_ACTIVO_FK Foreign Key (TIPO_ACTIVO) REFERENCES MASTER_TIPO_ACTIVO (VALOR);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_SUBTIPO_ACTIVO_FK Foreign Key (SUBTIPO_ACTIVO) REFERENCES MASTER_SUBTIPO_ACTIVO (VALOR);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_MONEDA_FK Foreign Key (MONEDA) REFERENCES MASTER_MONEDA (VALOR);
ALTER TABLE MASTER_PRODUCTOS ADD CONSTRAINT MASTER_PRODUCTOS_USO_INGRESOS_FK Foreign Key (USO_INGRESOS) REFERENCES MASTER_USO_INGRESOS (VALOR);
--
--
--
CREATE TABLE SCRAP_PRECIOS
(
	IDENTIFICADOR VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	VALOR_TITULO DOUBLE PRECISION NOT NULL,
	FECHA_VALOR DATE NOT NULL,
	ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL
);
ALTER TABLE SCRAP_PRECIOS ADD CONSTRAINT SCRAP_PRECIOS_IDENTIFICADOR_PK Primary Key (IDENTIFICADOR);
ALTER TABLE SCRAP_PRECIOS ADD CONSTRAINT SCRAP_PRECIOS_IDENTIFICADOR_FK Foreign Key (IDENTIFICADOR) REFERENCES MASTER_PRODUCTOS (IDENTIFICADOR);
ALTER TABLE SCRAP_PRECIOS ADD CONSTRAINT SCRAP_PRECIOS_NOMBRE_UNQ Unique (NOMBRE);
--
--
--
CREATE TABLE MASTER_MOVIMIENTOS
(
	MOVIMIENTO_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	IDENTIFICADOR VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	COMPRA_VENTA VARCHAR(25) NOT NULL,
	FECHA DATE NOT NULL,
	NUMERO_TITULOS DOUBLE PRECISION NOT NULL,
	PRECIO_TITULO DOUBLE PRECISION NOT NULL,	
	COMISION DOUBLE PRECISION NOT NULL,	
	TOTAL DOUBLE PRECISION NOT NULL,
	COMERCIALIZADOR VARCHAR(50) NOT NULL,
	MERCADO VARCHAR(50) NOT NULL
);
ALTER TABLE MASTER_MOVIMIENTOS ADD CONSTRAINT MASTER_MOVIMIENTOS_MOVIMIENTO_ID_PK Primary Key (MOVIMIENTO_ID);
ALTER TABLE MASTER_MOVIMIENTOS ADD CONSTRAINT MASTER_MOVIMIENTOS_IDENTIFICADOR_FK Foreign Key (IDENTIFICADOR) REFERENCES MASTER_PRODUCTOS (IDENTIFICADOR);
ALTER TABLE MASTER_MOVIMIENTOS ADD CONSTRAINT MASTER_MOVIMIENTOS_COMPRA_VENTA_FK Foreign Key (COMPRA_VENTA) REFERENCES MASTER_COMPRA_VENTA (VALOR);
ALTER TABLE MASTER_MOVIMIENTOS ADD CONSTRAINT MASTER_MOVIMIENTOS_COMERCIALIZADOR_FK Foreign Key (COMERCIALIZADOR) REFERENCES MASTER_COMERCIALIZADOR (VALOR);
ALTER TABLE MASTER_MOVIMIENTOS ADD CONSTRAINT MASTER_MOVIMIENTOS_MERCADO_FK Foreign Key (MERCADO) REFERENCES MASTER_MERCADO (VALOR);
--
--
--
COMMIT;
