/**
 * 
 */
package jsm.mdata.selenium.screenshot.common;

import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jsm.mdata.selenium.screenshot.base.URLGroup;
import jsm.mdata.selenium.screenshot.base.WebDriverBase;

/**
 * @author Empleado
 *
 */
public class DCWebUrlFromNombreEmpresa
{

	/**
	 * Logger
	 */
	private final static Logger LOGGER = LoggerFactory.getLogger(DCWebUrlFromNombreEmpresa.class);

	/**
	 * Configuración
	 */
	private final static Random RANDOM = new Random();
	private final static List<URLGroup> LISTA_EMPRESAS_GROUP = new ArrayList<URLGroup>();
	private final static List<String[]> LISTA_PROVEEDORES_DATOS = new ArrayList<String[]>();
	static
	{
		// --
		// -- LISTA PROVEEDORES DATOS
		// --
		LISTA_PROVEEDORES_DATOS.add(new String[] { "es.finance.yahoo.com", "finance.yahoo.com/quote/" });
		LISTA_PROVEEDORES_DATOS.add(new String[] { "es.investing.com", "investing.com/equities/" });
		// --
		// -- LISTA DE EMPRESAS
		// --
		List<String> listaEmpresas = new ArrayList<String>();
		// listaEmpresas.add("1ST SOURCE CORP");
		// listaEmpresas.add("3I GROUP PLC");
		// listaEmpresas.add("3I INFRASTRUCTURE PLC");
		// listaEmpresas.add("3M CO");
		// listaEmpresas.add("4IMPRINT PLC");
		// listaEmpresas.add("AALBERTS INDUSTRIES NV");
		// listaEmpresas.add("AARON'S INC");
		// listaEmpresas.add("ABBOTT LABORATORIES");
		// listaEmpresas.add("ABBVIE INC");
		// listaEmpresas.add("ABCAM PLC");
		// listaEmpresas.add("ABERDEEN ASSET MANAGEMENT");
		// listaEmpresas.add("ABERDEEN NEW DAWN INVESTMENT TRUST PLC");
		// listaEmpresas.add("ABM INDUSTRIES INC");
		// listaEmpresas.add("ACCENTURE");
		// listaEmpresas.add("ACCENTURE PLC");
		// listaEmpresas.add("ACCIONA");
		// listaEmpresas.add("ACCOR SA");
		// listaEmpresas.add("ACERINOX");
		// listaEmpresas.add("ACKERMANS & VAN HAAREN NV");
		// listaEmpresas.add("ACME UNITED CORP");
		// listaEmpresas.add("ACS");
		// listaEmpresas.add("ACTIVISION BLIZZARD INC");
		// listaEmpresas.add("ADIDAS");
		// listaEmpresas.add("ADIDAS AG");
		// listaEmpresas.add("ADOLFO DOMINGUEZ");
		// listaEmpresas.add("AEGON");
		// listaEmpresas.add("AEGON NV");
		// listaEmpresas.add("AENA");
		// listaEmpresas.add("AFLAC INC");
		// listaEmpresas.add("AG BARR PLC");
		// listaEmpresas.add("AGEAS NV");
		// listaEmpresas.add("AHOLD");
		// listaEmpresas.add("AHOLD NV");
		// listaEmpresas.add("AIR LIQUIDE SA");
		// listaEmpresas.add("AIR PRODUCTS & CHEM");
		// listaEmpresas.add("AIR PRODUCTS & CHEMICALS INC");
		// listaEmpresas.add("AIRBUS");
		// listaEmpresas.add("AIRBUS SE");
		// listaEmpresas.add("AKZO NOBEL NV");
		// listaEmpresas.add("ALBA");
		// listaEmpresas.add("ALBEMARLE CORP");
		// listaEmpresas.add("ALFA LAVAL");
		// listaEmpresas.add("ALGONQUIN POWER & UTILITIES CORP");
		// listaEmpresas.add("ALIMENTATION COUCHE TARD INC");
		// listaEmpresas.add("ALLIANCE TRUST PLC");
		// listaEmpresas.add("ALLIANT ENERGY CORP");
		// listaEmpresas.add("ALLIANZ");
		// listaEmpresas.add("ALLIANZ SE");
		// listaEmpresas.add("ALLIED PROPERTIES REAL ESTATE INVESTMENT TRUST");
		// listaEmpresas.add("ALMIRALL");
		// listaEmpresas.add("ALTRIA GROUP INC");
		// listaEmpresas.add("AMADEUS");
		// listaEmpresas.add("AMADEUS IT GROUP SA");
		// listaEmpresas.add("AMCOR");
		// listaEmpresas.add("AMERICAN EQUITY INVESTMENT LIFE HOLDING CO");
		// listaEmpresas.add("AMERICAN EXPRESS");
		// listaEmpresas.add("AMERICAN EXPRESS CO");
		// listaEmpresas.add("AMERICAN FINANCIAL GROUP INC");
		// listaEmpresas.add("AMERICAN STATES WATER");
		// listaEmpresas.add("AMERICAN STATES WATER CO");
		// listaEmpresas.add("AMERICAN TOWER");
		// listaEmpresas.add("AMERICAN WATER WORKS");
		// listaEmpresas.add("AMERIPRISE FINANCIAL");
		// listaEmpresas.add("AMERIPRISE FINANCIAL INC");
		// listaEmpresas.add("AMERISOURCEBERGEN CORP");
		// listaEmpresas.add("AMGEN INC");
		// listaEmpresas.add("AMPER");
		// listaEmpresas.add("ANALOG DEVICES INC");
		// listaEmpresas.add("ANDERSONS INC");
		// listaEmpresas.add("ANDREW PELLER LTD");
		// listaEmpresas.add("ANHEUSER BUSCH INBEV");
		// listaEmpresas.add("ANPARIO PLC");
		// listaEmpresas.add("AO SMITH CORP");
		// listaEmpresas.add("APPLE INC");
		// listaEmpresas.add("APPLIED INDUSTRIAL TECHNOLOGIES INC");
		// listaEmpresas.add("APPLIED MATERIALS");
		// listaEmpresas.add("APTARGROUP INC");
		// listaEmpresas.add("AQUA AMERICA INC");
		// listaEmpresas.add("ARCELORMITTAL");
		// listaEmpresas.add("ARCHER DANIELS MIDLAND");
		// listaEmpresas.add("ARCHER DANIELS MIDLAND CO");
		// listaEmpresas.add("ARKEMA SA");
		// listaEmpresas.add("ARMANINO FOODS OF DISTINCTION INC");
		// listaEmpresas.add("ARROW FINANCIAL CORP");
		// listaEmpresas.add("ARTESIAN RESOURCES");
		// listaEmpresas.add("ASHLAND GLOBAL HOLDINGS INC");
		// listaEmpresas.add("ASHMORE GROUP PLC");
		// listaEmpresas.add("ASHTEAD GROUP PLC");
		// listaEmpresas.add("ASML HOLDING NV");
		// listaEmpresas.add("ASSICURAZIONI GENERALI SPA");
		// listaEmpresas.add("ASSOCIATED BRITISH FOODS PLC");
		// listaEmpresas.add("ASSURANT INC");
		// listaEmpresas.add("ASTRAZENECA PLC");
		// listaEmpresas.add("AT&T INC");
		// listaEmpresas.add("ATCO LTD");
		// listaEmpresas.add("ATLANTIA SPA");
		// listaEmpresas.add("ATLAS COPCO");
		// listaEmpresas.add("ATMOS ENERGY");
		// listaEmpresas.add("ATOS SE");
		// listaEmpresas.add("ATRESMEDIA");
		// listaEmpresas.add("ATRION CORP");
		// listaEmpresas.add("ATRIUM EUROPEAN REAL ESTATES ");
		// listaEmpresas.add("ATRIUM MORTGAGE INVESTMENT CORP");
		// listaEmpresas.add("AUBURN NATIONAL BANCORP");
		// listaEmpresas.add("AUTOMATIC DATA PROC");
		// listaEmpresas.add("AUTOMATIC DATA PROCESSING INC");
		// listaEmpresas.add("AVISTA CORP");
		// listaEmpresas.add("AVIVA");
		// listaEmpresas.add("AXA");
		// listaEmpresas.add("AXA SA");
		// listaEmpresas.add("AXEL SPRINGER SE");
		// listaEmpresas.add("AXIS CAPITAL HOLDINGS LTD");
		// listaEmpresas.add("B&G FOODS");
		// listaEmpresas.add("BADGER METER INC");
		// listaEmpresas.add("BAE SYSTEMS PLC");
		// listaEmpresas.add("BAKKAFROST");
		// listaEmpresas.add("BALCHEM INC");
		// listaEmpresas.add("BALL CORP");
		// listaEmpresas.add("BALOISE HOLDING AG");
		// listaEmpresas.add("BANCFIRST CORP");
		// listaEmpresas.add("BANCFIRST CORP OK");
		// listaEmpresas.add("BANCO SABADELL");
		// listaEmpresas.add("BANCO SANTANDER");
		// listaEmpresas.add("BANK OF AMERICA");
		// listaEmpresas.add("BANK OF MARIN BANCORP");
		// listaEmpresas.add("BANK OF MONTREAL");
		// listaEmpresas.add("BANK OF NOVA SCOTIA");
		// listaEmpresas.add("BANK OF UTICA");
		// listaEmpresas.add("BANK OZK");
		// listaEmpresas.add("BANKERS INVESTMENT TRUST PLC");
		// listaEmpresas.add("BANKIA");
		// listaEmpresas.add("BANKINTER");
		// listaEmpresas.add("BAR HARBOR BANKSHARES");
		// listaEmpresas.add("BARRICK GOLD");
		// listaEmpresas.add("BARÓN DE LEY");
		// listaEmpresas.add("BASF");
		// listaEmpresas.add("BASF SE");
		// listaEmpresas.add("BAYER AG");
		// listaEmpresas.add("BAYER AKTIENGESELLSCHAFT");
		// listaEmpresas.add("BBVA");
		// listaEmpresas.add("BCE INC");
		// listaEmpresas.add("BEAZLEY PLC");
		// listaEmpresas.add("BECTON DICKINSON & CO");
		// listaEmpresas.add("BEIERSDORF AG");
		// listaEmpresas.add("BELLWAY PLC");
		// listaEmpresas.add("BEMIS CO");
		// listaEmpresas.add("BEMIS CO INC");
		// listaEmpresas.add("BEST BUY CORP");
		// listaEmpresas.add("BHP BILLITON");
		// listaEmpresas.add("BIC");
		// listaEmpresas.add("BIOMERIEUX SA");
		// listaEmpresas.add("BIOSEARCH");
		// listaEmpresas.add("BLACK HILLS CORP");
		// listaEmpresas.add("BLACK ROCK INC");
		// listaEmpresas.add("BLACKROCK INC");
		// listaEmpresas.add("BLOOMSBURY PUBLISHING PLC");
		// listaEmpresas.add("BME");
		// listaEmpresas.add("BMW");
		// listaEmpresas.add("BNP PARIBAS SA");
		// listaEmpresas.add("BODEGAS RIOJANAS");
		// listaEmpresas.add("BOEING");
		// listaEmpresas.add("BOK FINANCIAL CORP");
		// listaEmpresas.add("BORGWARNER");
		// listaEmpresas.add("BOUYGUES SA");
		// listaEmpresas.add("BOVIS HOMES GROUP PLC");
		// listaEmpresas.add("BOYD GROUP INCOME FUND");
		// listaEmpresas.add("BP PLC");
		// listaEmpresas.add("BRADY CORP");
		// listaEmpresas.add("BREMBO");
		// listaEmpresas.add("BRENNTAG AG");
		// listaEmpresas.add("BRIDGEMARQ REAL ESTATE SERVICES INC");
		// listaEmpresas.add("BRINKER INTERNATIONAL");
		// listaEmpresas.add("BRISTOL MYERS");
		// listaEmpresas.add("BRISTOL MYERS SQUIBB CO");
		// listaEmpresas.add("BRITISH AMERICAN TOBACCO PLC");
		// listaEmpresas.add("BRITISH AMERICAN TOBACCO PLC ADS COMMON STOCK");
		// listaEmpresas.add("BRITISH LAND CO PLC");
		// listaEmpresas.add("BRITVIC PLC");
		// listaEmpresas.add("BROADCOM INC");
		// listaEmpresas.add("BROADRIDGE FINANCIAL SOLUTIONS INC");
		// listaEmpresas.add("BROOKFIELD ASSET MANAGEMENT INC");
		// listaEmpresas.add("BROOKFIELD INFRAESTRUCTURE PARTNERS");
		// listaEmpresas.add("BROOKFIELD INFRASTRUCTURE PARTNERS LP");
		// listaEmpresas.add("BROOKFIELD PROPERTY PARTNERS LP");
		// listaEmpresas.add("BROOKFIELD RENEWABLE ENERGY PARTNERS LP");
		// listaEmpresas.add("BROOKFIELD RENEWABLE PARTNERS LP");
		// listaEmpresas.add("BROOKS MACDONALD PLC");
		// listaEmpresas.add("BROWN & BROWN INC");
		// listaEmpresas.add("BROWN FORMAN CLASS B");
		// listaEmpresas.add("BROWN FORMAN CORP");
		// listaEmpresas.add("BROWN FORMAN INC CLASS B");
		// listaEmpresas.add("BRUNNER INVESTMENT TRUST PLC");
		// listaEmpresas.add("BRUNSWICK CORP");
		// listaEmpresas.add("BT GROUP PLC");
		// listaEmpresas.add("BUCKEYE");
		// listaEmpresas.add("BUNGE LTD");
		// listaEmpresas.add("BUNZL PLC");
		// listaEmpresas.add("BURBERRY");
		// listaEmpresas.add("BUREAU VERITAS SA");
		// listaEmpresas.add("CAE INC");
		// listaEmpresas.add("CAESARSTONE");
		// listaEmpresas.add("CAF");
		// listaEmpresas.add("CAIXABANK");
		// listaEmpresas.add("CAL MAINE FOODS");
		// listaEmpresas.add("CALEDONIA INVESTMENTS PLC");
		// listaEmpresas.add("CALIFORNIA WATER SERVICE");
		// listaEmpresas.add("CALIFORNIA WATER SERVICE GROUP");
		// listaEmpresas.add("CALVIN B TAYLOR BANKSHARES INC");
		// listaEmpresas.add("CAMBRIDGE BANCORP");
		// listaEmpresas.add("CAMPARI");
		// listaEmpresas.add("CANADIAN APARTMENT PROPERTIES REAL ESTATE INVESTMENT TRUST");
		// listaEmpresas.add("CANADIAN GENERAL INVESTMENTS LTD");
		// listaEmpresas.add("CANADIAN IMPERIAL BANK OF COMMERCE");
		// listaEmpresas.add("CANADIAN NATIONAL RAILWAY");
		// listaEmpresas.add("CANADIAN NATIONAL RAILWAY CO");
		// listaEmpresas.add("CANADIAN NATURAL RESOURCES");
		// listaEmpresas.add("CANADIAN TIRE CORP LTD A NVTG");
		// listaEmpresas.add("CANADIAN UTILITIES");
		// listaEmpresas.add("CANADIAN WESTERN BANK");
		// listaEmpresas.add("CANTEL MEDICAL CORP");
		// listaEmpresas.add("CAPGEMINI SE");
		// listaEmpresas.add("CAPITAL POWER CORP");
		// listaEmpresas.add("CARDINAL HEALTH INC");
		// listaEmpresas.add("CARETECH HOLDINGS PLC");
		// listaEmpresas.add("CARLISLE COMPANIES");
		// listaEmpresas.add("CARLSBERG A/S CLASS B");
		// listaEmpresas.add("CARNIVAL");
		// listaEmpresas.add("CASEY'S GENERAL STORES INC");
		// listaEmpresas.add("CASINO GUICHARD PERRACHON SA");
		// listaEmpresas.add("CASS INFORMATION SYSTEMS INC");
		// listaEmpresas.add("CATALANA OCCIDENTE");
		// listaEmpresas.add("CATERPILLAR INC");
		// listaEmpresas.add("CBOE HOLDINGS INC");
		// listaEmpresas.add("CCFNB BANCORP INC");
		// listaEmpresas.add("CCL INDUSTRIES INC");
		// listaEmpresas.add("CELANESE CORP");
		// listaEmpresas.add("CELLNEX");
		// listaEmpresas.add("CENTERPOINT ENERGY");
		// listaEmpresas.add("CENTERPOINT ENERGY INC");
		// listaEmpresas.add("CENTRICA");
		// listaEmpresas.add("CF INDUSTRIES");
		// listaEmpresas.add("CH ROBINSON WORLDWIDE");
		// listaEmpresas.add("CHEMED CORP");
		// listaEmpresas.add("CHESAPEAKE FINANCIAL SHARES");
		// listaEmpresas.add("CHESAPEAKE UTILITIES");
		// listaEmpresas.add("CHESNARA PLC");
		// listaEmpresas.add("CHEVRON CORP");
		// listaEmpresas.add("CHICO'S FAS INC");
		// listaEmpresas.add("CHIPOTLE");
		// listaEmpresas.add("CHOCOLADEFABRIKEN LINDT & SPRUENGLI AG PARTICIPATION");
		// listaEmpresas.add("CHUBB LTD");
		// listaEmpresas.add("CHURCH & DWIGHT");
		// listaEmpresas.add("CHURCH & DWIGHT CO INC");
		// listaEmpresas.add("CIE AUTOMOTIVE");
		// listaEmpresas.add("CINCINNATI FINANCIAL");
		// listaEmpresas.add("CINCINNATI FINANCIAL CORP");
		// listaEmpresas.add("CINEPLEX INC");
		// listaEmpresas.add("CINTAS CORP");
		// listaEmpresas.add("CISCO SYSTEMS");
		// listaEmpresas.add("CISCO SYSTEMS INC");
		// listaEmpresas.add("CITIZENS FINANCIAL SERVICES");
		// listaEmpresas.add("CITY OF LONDON INVESTMENT TRUST PLC");
		// listaEmpresas.add("CLOROX CO");
		// listaEmpresas.add("CLOSE BROTHERS GROUP PLC");
		// listaEmpresas.add("CLÍNICA BAVIERA");
		// listaEmpresas.add("CMS ENERGY CORP");
		// listaEmpresas.add("CNP ASSURANCES SA");
		// listaEmpresas.add("COCA COLA");
		// listaEmpresas.add("COCA COLA CO");
		// listaEmpresas.add("COEMAC");
		// listaEmpresas.add("COGECO COMMUNICATIONS INC");
		// listaEmpresas.add("COGECO INC");
		// listaEmpresas.add("COHEN & STEERS INC");
		// listaEmpresas.add("COLGATE PALMOLIVE CO");
		// listaEmpresas.add("COLONIAL");
		// listaEmpresas.add("COLOPLAST A/S");
		// listaEmpresas.add("COLUMBIA SPORTSWEAR CO");
		// listaEmpresas.add("COMCAST CORP");
		// listaEmpresas.add("COMERICA INC");
		// listaEmpresas.add("COMMERCE BANCSHARES");
		// listaEmpresas.add("COMMERCE BANCSHARES INC");
		// listaEmpresas.add("COMMUNITY BANK SYSTEM");
		// listaEmpresas.add("COMMUNITY TRUST BANC");
		// listaEmpresas.add("COMPAGNIE FINANCIERE RICHEMONT");
		// listaEmpresas.add("COMPAGNIE FINANCIERE RICHEMONT SA");
		// listaEmpresas.add("COMPAGNIE GENERALE DES ETABLISSEMENTS MICHELIN");
		// listaEmpresas.add("COMPAGNIE PLASTIC OMNIUM SA");
		// listaEmpresas.add("COMPASS GROUP PLC");
		// listaEmpresas.add("COMPASS MINERALS");
		// listaEmpresas.add("COMPASS MINERALS INTL INC");
		// listaEmpresas.add("COMPUTER SERVICES INC");
		// listaEmpresas.add("CONCURRENT TECHNOLOGIES PLC");
		// listaEmpresas.add("CONNECT GROUP PLC");
		// listaEmpresas.add("CONNECTICUT WATER SERVICE");
		// listaEmpresas.add("CONSOLIDATED EDISON");
		// listaEmpresas.add("CONSOLIDATED EDISON INC");
		// listaEmpresas.add("CONSTELLATION BRANDS INC A");
		// listaEmpresas.add("CONTINENTAL");
		// listaEmpresas.add("CONTINENTAL AG");
		// listaEmpresas.add("CORBY SPIRIT & WINE LTD");
		// listaEmpresas.add("CORESITE REALTY CORP");
		// listaEmpresas.add("CORNING INC");
		// listaEmpresas.add("CORPORACIÓN FINANCIERA ALBA");
		// listaEmpresas.add("CORREIOS");
		// listaEmpresas.add("CORTICEIRA AMORIM");
		// listaEmpresas.add("COSTCO");
		// listaEmpresas.add("COSTCO WHOLESALE");
		// listaEmpresas.add("CRACKER BARREL OLD COUNTRY");
		// listaEmpresas.add("CRACKER BARREL OLD COUNTRY STORE INC");
		// listaEmpresas.add("CRANEWARE PLC");
		// listaEmpresas.add("CRANSWICK PLC");
		// listaEmpresas.add("CREDIT AGRICOLE SA");
		// listaEmpresas.add("CRH PLC");
		// listaEmpresas.add("CRODA INTERNATIONAL PLC");
		// listaEmpresas.add("CSX");
		// listaEmpresas.add("CSX CORP");
		// listaEmpresas.add("CT REAL ESTATE INVESTMENT TRUST");
		// listaEmpresas.add("CUBESMART");
		// listaEmpresas.add("CULLEN/FROST BANKERS");
		// listaEmpresas.add("CUMMINS INC");
		// listaEmpresas.add("CVS HEALTH CORP");
		// listaEmpresas.add("D'IETEREN SA");
		// listaEmpresas.add("DAIMLER AG");
		// listaEmpresas.add("DANONE");
		// listaEmpresas.add("DANONE SA");
		// listaEmpresas.add("DASSAULT AVIATION SA");
		// listaEmpresas.add("DASSAULT SYSTEMES SE");
		// listaEmpresas.add("DAVIDE CAMPARI MILANO SPA");
		// listaEmpresas.add("DAVITA HEALTHCARE");
		// listaEmpresas.add("DECHRA PHARMACEUTICALS PLC");
		// listaEmpresas.add("DEERE");
		// listaEmpresas.add("DEOLEO");
		// listaEmpresas.add("DERWENT LONDON");
		// listaEmpresas.add("DEUTSCHE BOERSE AG");
		// listaEmpresas.add("DEUTSCHE EUROSHOP AG");
		// listaEmpresas.add("DEUTSCHE POST");
		// listaEmpresas.add("DEUTSCHE POST AG");
		// listaEmpresas.add("DEUTSCHE TELEKOM");
		// listaEmpresas.add("DEUTSCHE TELEKOM AG");
		// listaEmpresas.add("DEUTSCHE WOHNEN SE");
		// listaEmpresas.add("DEWHURST PLC");
		// listaEmpresas.add("DIA");
		// listaEmpresas.add("DIAGEO PLC");
		// listaEmpresas.add("DIGITAL REALTY TRUST");
		// listaEmpresas.add("DIPLOMA PLC");
		// listaEmpresas.add("DISCOVER FINANCIAL SERVICES");
		// listaEmpresas.add("DLR");
		// listaEmpresas.add("DOLLAR GENERAL");
		// listaEmpresas.add("DOLLARAMA INC");
		// listaEmpresas.add("DOMINION ENERGY");
		// listaEmpresas.add("DOMINION ENERGY INC");
		// listaEmpresas.add("DOMINO'S PIZZA GROUP PLC");
		// listaEmpresas.add("DOMTAR CORP");
		// listaEmpresas.add("DONALDSON CO");
		// listaEmpresas.add("DONEGAL GROUP INC A");
		// listaEmpresas.add("DONEGAL GROUP INC B");
		// listaEmpresas.add("DOUGLAS DYNAMICS INC");
		// listaEmpresas.add("DOVER CORP");
		// listaEmpresas.add("DOW INC");
		// listaEmpresas.add("DS SMITH PLC");
		// listaEmpresas.add("DSV A/S");
		// listaEmpresas.add("DTE ENERGY CO");
		// listaEmpresas.add("DUKE ENERGY CORP");
		// listaEmpresas.add("DUNELM GROUP PLC");
		// listaEmpresas.add("DURO FELGUERA");
		// listaEmpresas.add("EAGLE BANCORP MONTANA INC");
		// listaEmpresas.add("EAGLE FINANCIAL SERVICES");
		// listaEmpresas.add("EATON CORP PLC");
		// listaEmpresas.add("EATON VANCE CORP");
		// listaEmpresas.add("EBRO FOODS");
		// listaEmpresas.add("ECOLAB INC");
		// listaEmpresas.add("EDINBURGH INVESTMENT TRUST PLC");
		// listaEmpresas.add("EDISON INTERNACIONAL");
		// listaEmpresas.add("EDISON INTERNATIONAL");
		// listaEmpresas.add("EDP ENERGIAS DE PORTUGAL SA");
		// listaEmpresas.add("EDP ENERGIAS DE PORTUGAL SA");
		// listaEmpresas.add("EIFFAGE SA");
		// listaEmpresas.add("ELECNOR");
		// listaEmpresas.add("ELI LILLY & CO");
		// listaEmpresas.add("ELIA SYSTEM OPERATOR NV");
		// listaEmpresas.add("ELISA OYJ");
		// listaEmpresas.add("EMERA INC");
		// listaEmpresas.add("EMERSON ELECTRIC");
		// listaEmpresas.add("EMERSON ELECTRIC CO");
		// listaEmpresas.add("EMPIRE CO LTD");
		// listaEmpresas.add("EMS CHEMIE HOLDING AG");
		// listaEmpresas.add("ENAGAS");
		// listaEmpresas.add("ENAGAS SA");
		// listaEmpresas.add("ENBRIDGE");
		// listaEmpresas.add("ENBRIDGE INC");
		// listaEmpresas.add("ENCE");
		// listaEmpresas.add("ENDESA");
		// listaEmpresas.add("ENEL SPA");
		// listaEmpresas.add("ENERGY TRANSFER LP");
		// listaEmpresas.add("ENGHOUSE SYSTEMS LTD");
		// listaEmpresas.add("ENGIE");
		// listaEmpresas.add("ENSIGN GROUP INC");
		// listaEmpresas.add("ENTERPRISE BANCORP INC");
		// listaEmpresas.add("ENTERPRISE PRODUCTS PARTNERS LP");
		// listaEmpresas.add("EON");
		// listaEmpresas.add("EQUITABLE GROUP INC");
		// listaEmpresas.add("EQUITY LIFESTYLE PROPERTIES");
		// listaEmpresas.add("ERCROS");
		// listaEmpresas.add("ERG SPA");
		// listaEmpresas.add("ERIE INDEMNITY CO");
		// listaEmpresas.add("ESSENTRA");
		// listaEmpresas.add("ESSEX PROPERTY TRUST");
		// listaEmpresas.add("ESSILOR");
		// listaEmpresas.add("ESSILOR LUXOTTICA");
		// listaEmpresas.add("ESSILORLUXOTTICA SA");
		// listaEmpresas.add("ETABL FRANZ COLRUYT NV");
		// listaEmpresas.add("EUROFINS SCIENTIFIC SE");
		// listaEmpresas.add("EURONEXT");
		// listaEmpresas.add("EUTELSAT COMMUNICATIONS SA");
		// listaEmpresas.add("EVERCORE PARTNERS INC");
		// listaEmpresas.add("EVERGY INC");
		// listaEmpresas.add("EVERSOURCE ENERGY");
		// listaEmpresas.add("EVONIK INDUSTRIES AG");
		// listaEmpresas.add("EXCHANGE INCOME CORP");
		// listaEmpresas.add("EXCO TECHNOLOGIES LTD");
		// listaEmpresas.add("EXPEDITORS INTERNATIONAL");
		// listaEmpresas.add("EXTRA SPACE STORAGE INC");
		// listaEmpresas.add("EXXON MOBIL CORP");
		// listaEmpresas.add("EXXONMOBIL CORP");
		// listaEmpresas.add("F&C CAPITAL & INCOME INVESTMENT TRUST PLC");
		// listaEmpresas.add("FACTSET RESEARCH SYSTEM INC");
		// listaEmpresas.add("FAES");
		// listaEmpresas.add("FARMERS & MERCHANTS BANCORP");
		// listaEmpresas.add("FASTENAL");
		// listaEmpresas.add("FASTENAL CO");
		// listaEmpresas.add("FAURECIA SA");
		// listaEmpresas.add("FCC");
		// listaEmpresas.add("FEDERAL REALTY INV TRUST");
		// listaEmpresas.add("FEDERAL REALTY INVESTMENT TRUST");
		// listaEmpresas.add("FEDEX CORP");
		// listaEmpresas.add("FERROVIAL");
		// listaEmpresas.add("FIELMANN AG");
		// listaEmpresas.add("FIELMANN AKTIENGESELLSCHAFT");
		// listaEmpresas.add("FIERA CAPITAL CORP");
		// listaEmpresas.add("FINNING INTERNATIONAL");
		// listaEmpresas.add("FIRM CAPITAL PROPERTY TRUST");
		// listaEmpresas.add("FIRST DERIVATIVES PLC");
		// listaEmpresas.add("FIRST FARMERS FINANCIAL CORP");
		// listaEmpresas.add("FIRST FINANCIAL CORP");
		// listaEmpresas.add("FIRST INTERSTATE BANCSYSTEM INC");
		// listaEmpresas.add("FIRST NATIONAL FINANCIAL CORP");
		// listaEmpresas.add("FIRST OF LONG ISLAND CORP");
		// listaEmpresas.add("FLOWERS FOODS");
		// listaEmpresas.add("FLOWERS FOODS INC");
		// listaEmpresas.add("FLUIDRA");
		// listaEmpresas.add("FLUTTER ENTERTAINMENT PLC");
		// listaEmpresas.add("FORTIS");
		// listaEmpresas.add("FORTIS INC");
		// listaEmpresas.add("FORTUM OYJ");
		// listaEmpresas.add("FRANCO NEVADA CORP");
		// listaEmpresas.add("FRANKLIN ELECTRIC CO");
		// listaEmpresas.add("FRANKLIN RESOURCES");
		// listaEmpresas.add("FRANKLIN RESOURCES INC");
		// listaEmpresas.add("FRAPORT AG");
		// listaEmpresas.add("FRAPORT AG FRANKFURT ARPRT SVCS WRLDWDE");
		// listaEmpresas.add("FREENET AG");
		// listaEmpresas.add("FRESENIUS MEDICAL CARE");
		// listaEmpresas.add("FRESENIUS MEDICAL CARE AG & CO KGAA");
		// listaEmpresas.add("FRESENIUS SE & CO KGAA");
		// listaEmpresas.add("FUCHS PETROLUB SE");
		// listaEmpresas.add("FUCHS PETROLUB SE PREF");
		// listaEmpresas.add("FUCHS PETROLUB SE PREFERRED");
		// listaEmpresas.add("G4S PLC");
		// listaEmpresas.add("GALP ENERGIA SGPS SA");
		// listaEmpresas.add("GAMESA");
		// listaEmpresas.add("GEA GROUP AKTIENGESELLSCHAFT");
		// listaEmpresas.add("GECINA SA");
		// listaEmpresas.add("GENERAL DYNAMICS");
		// listaEmpresas.add("GENERAL DYNAMICS CORP");
		// listaEmpresas.add("GENERAL ELECTRIC");
		// listaEmpresas.add("GENERAL MILLS INC");
		// listaEmpresas.add("GENTEX");
		// listaEmpresas.add("GENUINE PARTS CO");
		// listaEmpresas.add("GENUS PLC");
		// listaEmpresas.add("GENWORTH MI CANADA INC");
		// listaEmpresas.add("GEORGE WESTON LTD");
		// listaEmpresas.add("GESTAMP");
		// listaEmpresas.add("GETLINK SE");
		// listaEmpresas.add("GILDAN ACTIVEWEAR INC");
		// listaEmpresas.add("GILEAD SCIENCES INC");
		// listaEmpresas.add("GIVAUDAN");
		// listaEmpresas.add("GIVAUDAN SA");
		// listaEmpresas.add("GLANBIA PLC");
		// listaEmpresas.add("GLAXO SMITH KLINE");
		// listaEmpresas.add("GLAXOSMITHKLINE PLC");
		// listaEmpresas.add("GLENCORE");
		// listaEmpresas.add("GLOBAL WATER RESOURCES INC");
		// listaEmpresas.add("GLOBE LIFE INC");
		// listaEmpresas.add("GN STORE NORD A/S");
		// listaEmpresas.add("GOLDCORP");
		// listaEmpresas.add("GOLDMAN SACHS GROUP INC");
		// listaEmpresas.add("GOOGLE");
		// listaEmpresas.add("GORMAN RUPP CO");
		// listaEmpresas.add("GRACO INC");
		// listaEmpresas.add("GRANITE REAL ESTATE INVESTMENT TRUST");
		// listaEmpresas.add("GREENE KING PLC");
		// listaEmpresas.add("GRIFOLS");
		// listaEmpresas.add("GROEP BRUSSEL LAMBERT NV");
		// listaEmpresas.add("GROUP 1 AUTOMOTIVE INC");
		// listaEmpresas.add("GROUPE BRUXELLES LAMBERT SA");
		// listaEmpresas.add("GUARDIAN CAPITAL GROUP LTD");
		// listaEmpresas.add("GULF MARINE SERVICES");
		// listaEmpresas.add("H&R BLOCK");
		// listaEmpresas.add("HALLIBURTON");
		// listaEmpresas.add("HALMA PLC");
		// listaEmpresas.add("HAMMERSON PLC");
		// listaEmpresas.add("HANESBRANDS INC");
		// listaEmpresas.add("HANNOVER RE");
		// listaEmpresas.add("HANOVER INSURANCE GROUP");
		// listaEmpresas.add("HARDWOODS DISTRIBUTION INC");
		// listaEmpresas.add("HARLEY DAVIDSON");
		// listaEmpresas.add("HASBRO");
		// listaEmpresas.add("HASBRO INC");
		// listaEmpresas.add("HAVERTY FURNITURE COMPANIES INC");
		// listaEmpresas.add("HAVERTY FURNITURE COMPANIES INC A");
		// listaEmpresas.add("HAWKINS INC");
		// listaEmpresas.add("HB FULLER CO");
		// listaEmpresas.add("HCP");
		// listaEmpresas.add("HDFC BANK LTD");
		// listaEmpresas.add("HEALTHCARE SERVICES GROUP INC");
		// listaEmpresas.add("HEICO CORP");
		// listaEmpresas.add("HEIDELBERGCEMENT AG");
		// listaEmpresas.add("HEINEKEN NV");
		// listaEmpresas.add("HELMERICH & PAYNE INC");
		// listaEmpresas.add("HENDERSON EUROTRUST PLC");
		// listaEmpresas.add("HENDERSON SMALLER COMPANIES INVESTMENT TRUST PLC");
		// listaEmpresas.add("HENKEL");
		// listaEmpresas.add("HENKEL AG & CO KGAA");
		// listaEmpresas.add("HENKEL AG & CO KGAA PREFERRED");
		// listaEmpresas.add("HENNES & MAURITZ AB");
		// listaEmpresas.add("HERA SPA");
		// listaEmpresas.add("HERMES INTERNATIONAL SCA");
		// listaEmpresas.add("HERSHEY CO");
		// listaEmpresas.add("HIGHCROFT INVESTMENTS PLC");
		// listaEmpresas.add("HILL & SMITH HOLDINGS PLC");
		// listaEmpresas.add("HILLENBRAND INC");
		// listaEmpresas.add("HILTON FOOD GROUP PLC");
		// listaEmpresas.add("HINGHAM INSTITUTION FOR SAVINGS");
		// listaEmpresas.add("HOCHTIEF AG");
		// listaEmpresas.add("HOLLY ENERGY PARTNERS LP");
		// listaEmpresas.add("HOME DEPOT INC");
		// listaEmpresas.add("HOME INVEST BELGIUM SA");
		// listaEmpresas.add("HONAT BANCORP INC");
		// listaEmpresas.add("HORACE MANN EDUCATORS CORP");
		// listaEmpresas.add("HORMEL FOODS CORP");
		// listaEmpresas.add("HOWDEN JOINERY");
		// listaEmpresas.add("HUBBELL INC");
		// listaEmpresas.add("HUGO BOSS");
		// listaEmpresas.add("IBERDROLA");
		// listaEmpresas.add("IBERDROLA SA");
		// listaEmpresas.add("IBERPAPEL");
		// listaEmpresas.add("IBM");
		// listaEmpresas.add("ICADE SA");
		// listaEmpresas.add("IDEX CORP");
		// listaEmpresas.add("ILIAD SA");
		// listaEmpresas.add("ILLINOIS TOOL WORKS");
		// listaEmpresas.add("ILLINOIS TOOL WORKS INC");
		// listaEmpresas.add("IMA INDUSTRIA MACCHINE AUTOMATICHE SPA");
		// listaEmpresas.add("IMERYS SA");
		// listaEmpresas.add("IMI PLC");
		// listaEmpresas.add("IMPERIAL BRANDS");
		// listaEmpresas.add("IMPERIAL BRANDS GROUP PLC");
		// listaEmpresas.add("IMPERIAL BRANDS PLC");
		// listaEmpresas.add("IMPERIAL OIL");
		// listaEmpresas.add("INCHCAPE PLC");
		// listaEmpresas.add("INDITEX");
		// listaEmpresas.add("INDITEX SA");
		// listaEmpresas.add("INDRA");
		// listaEmpresas.add("INDUSTRIAL ALLIANCE");
		// listaEmpresas.add("INFINEON TECHNOLOGIES AG");
		// listaEmpresas.add("INFORMA PLC");
		// listaEmpresas.add("INGENICO GROUP SA");
		// listaEmpresas.add("INGERSOLL RAND");
		// listaEmpresas.add("INGREDION INC");
		// listaEmpresas.add("INNERGEX RENEWABLE ENERGY INC");
		// listaEmpresas.add("INTACT FINANCIAL ");
		// listaEmpresas.add("INTEL");
		// listaEmpresas.add("INTEL CORP");
		// listaEmpresas.add("INTER PARFUMS INC");
		// listaEmpresas.add("INTER PIPELINE");
		// listaEmpresas.add("INTERNATIONAL BANCSHARES CORP");
		// listaEmpresas.add("INTERNATIONAL BUSINESS MACHINES");
		// listaEmpresas.add("INTERNATIONAL BUSINESS MACHINES CORP");
		// listaEmpresas.add("INTERNATIONAL FLAVORS & FRAGRANCES");
		// listaEmpresas.add("INTERNATIONAL SPEEDWAY CORP");
		// listaEmpresas.add("INTERRENT REAL ESTATE INVESTMENT TRUST");
		// listaEmpresas.add("INTERTEK GROUP PLC");
		// listaEmpresas.add("INVESCO INCOME GROWTH TRUST PLC");
		// listaEmpresas.add("INVESCO LTD");
		// listaEmpresas.add("INVESTEC PLC");
		// listaEmpresas.add("IPSEN SA");
		// listaEmpresas.add("ISABELLA BANK CORP");
		// listaEmpresas.add("J SMART & CO PLC");
		// listaEmpresas.add("J&J SNACK FOODS CORP");
		// listaEmpresas.add("JACK HENRY & ASSOCIATES");
		// listaEmpresas.add("JAMES FISHER & SONS PLC");
		// listaEmpresas.add("JB HUNT TRANSPORT SERVICES INC");
		// listaEmpresas.add("JCDECAUX SA");
		// listaEmpresas.add("JD SPORTS FASHION PLC");
		// listaEmpresas.add("JIANGSU EXPRESSWAY");
		// listaEmpresas.add("JM SMUCKER");
		// listaEmpresas.add("JM SMUCKER CO");
		// listaEmpresas.add("JOHN WILEY & SONS INC");
		// listaEmpresas.add("JOHNSON & JOHNSON");
		// listaEmpresas.add("JOHNSON CONTROLS");
		// listaEmpresas.add("JOHNSON MATTHEY PLC");
		// listaEmpresas.add("JP MORGAN CHASE & CO");
		// listaEmpresas.add("JPM CLAVERHOUSE INVESTMENT TRUST PLC");
		// listaEmpresas.add("JPMORGAN CHASE & CO");
		// listaEmpresas.add("JUDGES SCIENTIFIC PLC");
		// listaEmpresas.add("JUPITER FUND MANAGEMENT PLC");
		// listaEmpresas.add("KELLOGG CO");
		// listaEmpresas.add("KERING SA");
		// listaEmpresas.add("KERRY GROUP PLC");
		// listaEmpresas.add("KEYERA CORP");
		// listaEmpresas.add("KIMBERLY CLARK CORP");
		// listaEmpresas.add("KIMCO REALTY CORP");
		// listaEmpresas.add("KINDER MORGAN");
		// listaEmpresas.add("KINEPOLIS GROUP NV");
		// listaEmpresas.add("KINGFISHER PLC");
		// listaEmpresas.add("KION GROUP AG");
		// listaEmpresas.add("KLEPIERRE SA");
		// listaEmpresas.add("KOEBENHAVNS LUFTHAVNE A/S");
		// listaEmpresas.add("KONE OYJ");
		// listaEmpresas.add("KONECRANES OYJ");
		// listaEmpresas.add("KONECRANES PLC");
		// listaEmpresas.add("KONINKLIJKE DSM NV");
		// listaEmpresas.add("KONINKLIJKE VOPAK NV");
		// listaEmpresas.add("KORIAN SA");
		// listaEmpresas.add("KRAFT HEINZ CO");
		// listaEmpresas.add("KROGER CO");
		// listaEmpresas.add("L BRANDS");
		// listaEmpresas.add("L'OREAL");
		// listaEmpresas.add("L'OREAL SA");
		// listaEmpresas.add("L3HARRIS TECHNOLOGIES INC");
		// listaEmpresas.add("LAGARDERE SCA");
		// listaEmpresas.add("LANCASTER COLONY CORP");
		// listaEmpresas.add("LANDMARK BANCORP INC");
		// listaEmpresas.add("LANDSTAR SYSTEM INC");
		// listaEmpresas.add("LANXESS AG");
		// listaEmpresas.add("LAURENTIAN BANK OF CANADA");
		// listaEmpresas.add("LAZARD LTD");
		// listaEmpresas.add("LEAR CORP");
		// listaEmpresas.add("LEG IMMOBILIEN AG");
		// listaEmpresas.add("LEGAL & GENERAL GROUP PLC");
		// listaEmpresas.add("LEGAL&GENERAL");
		// listaEmpresas.add("LEGGETT & PLATT INC");
		// listaEmpresas.add("LENNOX INTERNATIONAL INC");
		// listaEmpresas.add("LIMONEIRA CO");
		// listaEmpresas.add("LINCOLN ELECTRIC HOLDINGS");
		// listaEmpresas.add("LINDE");
		// listaEmpresas.add("LINDE PLC");
		// listaEmpresas.add("LINDSAY CORP");
		// listaEmpresas.add("LINDT & SPRÜNGLI AG");
		// listaEmpresas.add("LINDT&SPRUNGLI");
		// listaEmpresas.add("LINGOTES ESPECIALES");
		// listaEmpresas.add("LITHIA MOTORS INC");
		// listaEmpresas.add("LITTELFUSE INC");
		// listaEmpresas.add("LOBLAW COMPANIES LTD");
		// listaEmpresas.add("LOCKHEED MARTIN");
		// listaEmpresas.add("LOGISTA");
		// listaEmpresas.add("LOGISTEC CORP");
		// listaEmpresas.add("LOTUS BAKERIES NV");
		// listaEmpresas.add("LOUIS VUITTON");
		// listaEmpresas.add("LOWE'S COMPANIES");
		// listaEmpresas.add("LOWE'S COMPANIES INC");
		// listaEmpresas.add("LOWE'S COS INC");
		// listaEmpresas.add("LSE");
		// listaEmpresas.add("LSL PROPERTIES");
		// listaEmpresas.add("LTC PROPERTIES INC");
		// listaEmpresas.add("LVMH SE");
		// listaEmpresas.add("LYONS BANCORP INC");
		// listaEmpresas.add("MAGELLAN AEROSPACE CORP");
		// listaEmpresas.add("MAGELLAN MIDSTREAM PARTNERS LP");
		// listaEmpresas.add("MAGNA INTERNATIONAL INC");
		// listaEmpresas.add("MAIN STREET CAPITAL CORP");
		// listaEmpresas.add("MAINTEL HOLDINGS PLC");
		// listaEmpresas.add("MAN SE");
		// listaEmpresas.add("MANPOWER GROUP");
		// listaEmpresas.add("MANULIFE FINANCIAL CORP");
		// listaEmpresas.add("MAPFRE");
		// listaEmpresas.add("MARKETAXESS HOLDINGS INC");
		// listaEmpresas.add("MARKS & SPENCER GROUP PLC");
		// listaEmpresas.add("MARRIOTT INTERNATIONAL INC");
		// listaEmpresas.add("MARSH & MCLENNAN COMPANIES INC");
		// listaEmpresas.add("MASTERCARD");
		// listaEmpresas.add("MATTHEWS INTERNATIONAL");
		// listaEmpresas.add("MATTIOLI WOODS PLC");
		// listaEmpresas.add("MAXIM INTEGRATED PRODUCTS");
		// listaEmpresas.add("MCCORMICK & CO");
		// listaEmpresas.add("MCCORMICK & CO INC");
		// listaEmpresas.add("MCDONALD'S CORP");
		// listaEmpresas.add("MCGRATH RENTCORP");
		// listaEmpresas.add("MCKESSON CORP");
		// listaEmpresas.add("MDU RESOURCES");
		// listaEmpresas.add("MDU RESOURCES GROUP INC");
		// listaEmpresas.add("MEARS GROUP PLC");
		// listaEmpresas.add("MEDIASET");
		// listaEmpresas.add("MEDIOBANCA GROUP");
		// listaEmpresas.add("MEDTRONIC PLC");
		// listaEmpresas.add("MEGGITT PLC");
		// listaEmpresas.add("MELIÁ HOTELS");
		// listaEmpresas.add("MERCK & CO INC");
		// listaEmpresas.add("MERCK KGAA");
		// listaEmpresas.add("MERCURY GENERAL CORP");
		// listaEmpresas.add("MEREDITH CORP");
		// listaEmpresas.add("MERLÍN PROPERTIES");
		// listaEmpresas.add("METHANEX CORP");
		// listaEmpresas.add("METLIFE");
		// listaEmpresas.add("METRO INC");
		// listaEmpresas.add("MGE ENERGY INC");
		// listaEmpresas.add("MICHAEL KORS");
		// listaEmpresas.add("MICHELIN");
		// listaEmpresas.add("MICHELIN SCA");
		// listaEmpresas.add("MICRO FOCUS INTERNATIONAL PLC");
		// listaEmpresas.add("MICROCHIP TECHNOLOGY INC");
		// listaEmpresas.add("MICROSOFT CO");
		// listaEmpresas.add("MICROSOFT CORP");
		// listaEmpresas.add("MIDDLESEX WATER CO");
		// listaEmpresas.add("MIQUEL Y COSTAS");
		// listaEmpresas.add("MOLSON COORS");
		// listaEmpresas.add("MONDELEZ INTERNATIONAL INC");
		// listaEmpresas.add("MONDI PLC");
		// listaEmpresas.add("MONEYSUPERMARKETCOM GROUP PLC");
		// listaEmpresas.add("MONRO INC");
		// listaEmpresas.add("MOODY'S CORP");
		// listaEmpresas.add("MOODYS");
		// listaEmpresas.add("MSA SAFETY INC");
		// listaEmpresas.add("MSC INDUSTRIAL DIRECT CO INC");
		// listaEmpresas.add("MUNCHENER RUCKVERSICHERUNGS GESELLSCHAFT AKTIENGESELLSCHAFT");
		// listaEmpresas.add("MUNCY BANK FINANCIAL INC");
		// listaEmpresas.add("MUNICH RE");
		// listaEmpresas.add("MUNICH REINSURANCE CO");
		// listaEmpresas.add("MURRAY INTERNATIONAL TRUST PLC");
		// listaEmpresas.add("NACCO INDUSTRIES");
		// listaEmpresas.add("NATIONAL BANK");
		// listaEmpresas.add("NATIONAL BANKSHARES");
		// listaEmpresas.add("NATIONAL FUEL GAS");
		// listaEmpresas.add("NATIONAL GRID");
		// listaEmpresas.add("NATIONAL HEALTH INVESTORS");
		// listaEmpresas.add("NATIONAL HEALTHCARE CORP");
		// listaEmpresas.add("NATIONAL RETAIL PROPERTIES");
		// listaEmpresas.add("NATRA");
		// listaEmpresas.add("NATURGY");
		// listaEmpresas.add("NESTLE");
		// listaEmpresas.add("NESTLE SA");
		// listaEmpresas.add("NEW JERSEY RESOURCES");
		// listaEmpresas.add("NEWMARKET CORP");
		// listaEmpresas.add("NEXT PLC");
		// listaEmpresas.add("NEXTERA ENERGY INC");
		// listaEmpresas.add("NH HOTELES");
		// listaEmpresas.add("NICHOLS PLC");
		// listaEmpresas.add("NIKE INC");
		// listaEmpresas.add("NOKIAN RENKAAT OYJ");
		// listaEmpresas.add("NOKIAN TYRES PLC");
		// listaEmpresas.add("NORDSON CORP");
		// listaEmpresas.add("NORTHEAST INDIANA BANCORP");
		// listaEmpresas.add("NORTHRIM BANCORP INC");
		// listaEmpresas.add("NORTHROP GRUMMAN");
		// listaEmpresas.add("NORTHWEST BANCSHARES INC");
		// listaEmpresas.add("NORTHWEST NATURAL GAS");
		// listaEmpresas.add("NORTHWEST NATURAL HOLDING CO");
		// listaEmpresas.add("NORTHWESTERN CORP");
		// listaEmpresas.add("NORWOOD FINANCIAL");
		// listaEmpresas.add("NOS");
		// listaEmpresas.add("NOVARTIS");
		// listaEmpresas.add("NOVARTIS AG");
		// listaEmpresas.add("NOVO NORDISK");
		// listaEmpresas.add("NOVO NORDISK A/S");
		// listaEmpresas.add("NOVOZYMES A/S");
		// listaEmpresas.add("NU SKIN ENTERPRISES INC");
		// listaEmpresas.add("NUCOR CORP");
		// listaEmpresas.add("OCCIDENTAL PETROLEUM");
		// listaEmpresas.add("OCCIDENTAL PETROLEUM CORP");
		// listaEmpresas.add("OENEO");
		// listaEmpresas.add("OGE ENERGY CORP");
		// listaEmpresas.add("OHL");
		// listaEmpresas.add("OIL DRI CORP OF AMERICA");
		// listaEmpresas.add("OLD REPUBLIC INTERNATIONAL");
		// listaEmpresas.add("OLD REPUBLIC INTERNATIONAL CORP");
		// listaEmpresas.add("OMEGA HEALTH CARE");
		// listaEmpresas.add("OMEGA HEALTHCARE INVESTORS");
		// listaEmpresas.add("OMNICOM GROUP INC");
		// listaEmpresas.add("ONEOK INC");
		// listaEmpresas.add("ONEX CORP");
		// listaEmpresas.add("OPEN TEXT CORP");
		// listaEmpresas.add("ORACLE CORP");
		// listaEmpresas.add("ORION OYJ");
		// listaEmpresas.add("ORKLA");
		// listaEmpresas.add("OSISKO GOLD ROYALTIES LTD");
		// listaEmpresas.add("OSRAM LICHT AG");
		// listaEmpresas.add("OSSUR HF");
		// listaEmpresas.add("OWENS & MINOR INC");
		// listaEmpresas.add("PANDORA");
		// listaEmpresas.add("PARKER HANNIFIN CORP");
		// listaEmpresas.add("PARKLAND FUEL CORP");
		// listaEmpresas.add("PARTNERS GROUP HOLDING");
		// listaEmpresas.add("PATTERN ENERGY GROUP INC");
		// listaEmpresas.add("PAYCHEX");
		// listaEmpresas.add("PAYPOINT PLC");
		// listaEmpresas.add("PEARSON");
		// listaEmpresas.add("PEMBINA PIPELINE");
		// listaEmpresas.add("PENNON GROUP PLC");
		// listaEmpresas.add("PENTAIR LTD");
		// listaEmpresas.add("PENTAIR PLC");
		// listaEmpresas.add("PEOPLE'S UNITED FINANCIAL");
		// listaEmpresas.add("PEOPLE'S UNITED FINANCIAL INC");
		// listaEmpresas.add("PEPSICO INC");
		// listaEmpresas.add("PERNOD RICARD");
		// listaEmpresas.add("PERNOD RICARD SA");
		// listaEmpresas.add("PERRIGO CO PLC");
		// listaEmpresas.add("PERSONAL GROUP HOLDINGS PLC");
		// listaEmpresas.add("PETMED EXPRESS INC");
		// listaEmpresas.add("PFIZER INC");
		// listaEmpresas.add("PHARMAMAR");
		// listaEmpresas.add("PHILIP MORRIS INTERNATIONAL");
		// listaEmpresas.add("PHILIP MORRIS INTERNATIONAL INC");
		// listaEmpresas.add("PHILIPS NV");
		// listaEmpresas.add("PILGRIM´S PRIDE");
		// listaEmpresas.add("PIONEER BANKSHARES INC");
		// listaEmpresas.add("PKG");
		// listaEmpresas.add("PLAYTECH PLC");
		// listaEmpresas.add("PLAZA RETAIL REIT");
		// listaEmpresas.add("POLARIS INDUSTRIES");
		// listaEmpresas.add("PORTLAND GENERAL ELECTRIC CO");
		// listaEmpresas.add("PPG INDUSTRIES INC");
		// listaEmpresas.add("PPL CORP");
		// listaEmpresas.add("PREFERRED APARTMENT COMMUNITIES INC");
		// listaEmpresas.add("PREMIUM BRANDS HOLDINGS CORP");
		listaEmpresas.add("PRIM");
		listaEmpresas.add("PRIMARY HEALTH PROPERTIES PLC");
		listaEmpresas.add("PRIMERICA INC");
		listaEmpresas.add("PRINCIPAL FINANCIAL GROUP");
		listaEmpresas.add("PRINCIPAL FINANCIAL GROUP INC");
		listaEmpresas.add("PRISA");
		listaEmpresas.add("PROCTER & GAMBLE CO");
		listaEmpresas.add("PROLOGIS");
		listaEmpresas.add("PROSEGUR");
		listaEmpresas.add("PROSPERITY BANCSHARES");
		listaEmpresas.add("PRUDENTIAL FINANCIAL INC");
		listaEmpresas.add("PRUDENTIAL PLC");
		listaEmpresas.add("PRYSMIAN SPA");
		listaEmpresas.add("PSB HOLDINGS INC");
		listaEmpresas.add("PUBLICIS GROUPE SA");
		listaEmpresas.add("PZ CUSSONS PLC");
		listaEmpresas.add("QUAINT OAK BANCORP INC");
		listaEmpresas.add("QUAKER CHEMICAL CORP");
		listaEmpresas.add("QUALCOMM INC");
		listaEmpresas.add("RANDSTAD");
		listaEmpresas.add("RANDSTAD NV");
		listaEmpresas.add("RAYTHEON CO");
		listaEmpresas.add("REALIA");
		listaEmpresas.add("REALTY INCOME CORP");
		listaEmpresas.add("RECKITT BECKINSER");
		listaEmpresas.add("RECKITT BENCKISER GROUP PLC");
		listaEmpresas.add("RECORDATI SPA");
		listaEmpresas.add("RED ELECTRICA");
		listaEmpresas.add("RED ELECTRICA CORPORACION SA");
		listaEmpresas.add("REGAL BELOIT CORP");
		listaEmpresas.add("REGIS");
		listaEmpresas.add("REIG JOFRE");
		listaEmpresas.add("REINSURANCE GROUP OF AMERICA INC");
		listaEmpresas.add("REMY COINTREAU SA");
		listaEmpresas.add("RENAISSANCERE HOLDINGS");
		listaEmpresas.add("RENAULT");
		listaEmpresas.add("RENAULT SA");
		listaEmpresas.add("RENTA 4");
		listaEmpresas.add("RENTA CORPORACIÓN");
		listaEmpresas.add("REPSOL");
		listaEmpresas.add("REPUBLIC BANCORP KY");
		listaEmpresas.add("REPUBLIC SERVICES INC");
		listaEmpresas.add("RESOURCES CONNECTION INC");
		listaEmpresas.add("RESTAURANT BRANDS");
		listaEmpresas.add("RETAIL OPPORTUNITY INVESTMENTS CORP");
		listaEmpresas.add("REXAM");
		listaEmpresas.add("RGC RESOURCES INC");
		listaEmpresas.add("RICHARDS PACKAGING INCOME FUND");
		listaEmpresas.add("RICHELIEU HARDWARE LTD");
		listaEmpresas.add("RIGHTMOVE PLC");
		listaEmpresas.add("RIO TINTO");
		listaEmpresas.add("RITCHIE BROS AUCTIONEERS INC");
		listaEmpresas.add("RITCHIE BROTHERS AUCTIONEERS INC");
		listaEmpresas.add("RLI CORP");
		listaEmpresas.add("ROBERT HALF INTERNATIONAL INC");
		listaEmpresas.add("ROCHE");
		listaEmpresas.add("ROCHE HOLDING LTD GENUSSSCHEINE");
		listaEmpresas.add("ROCKWELL AUTOMATION");
		listaEmpresas.add("ROCKWOOL INTERNATIONAL A/S CLASS B");
		listaEmpresas.add("ROLLINS INC");
		listaEmpresas.add("ROLLS ROYCE");
		listaEmpresas.add("ROPER TECHNOLOGIES INC");
		listaEmpresas.add("ROSS STORES INC");
		listaEmpresas.add("ROTORK PLC");
		listaEmpresas.add("ROVI");
		listaEmpresas.add("ROYAL BANK OF CANADA");
		listaEmpresas.add("ROYAL DSM NV");
		listaEmpresas.add("ROYAL DUTCH SHELL");
		listaEmpresas.add("ROYAL GOLD");
		listaEmpresas.add("ROYAL GOLD INC");
		listaEmpresas.add("ROYAL MAIL");
		listaEmpresas.add("ROYAL PHILIPS NV");
		listaEmpresas.add("ROYAL VOPAK NV");
		listaEmpresas.add("RPC GROUP PLC");
		listaEmpresas.add("RPM INTERNATIONAL INC");
		listaEmpresas.add("RPS GROUP PLC");
		listaEmpresas.add("RUBIS");
		listaEmpresas.add("RUBIS SCA");
		listaEmpresas.add("RWE");
		listaEmpresas.add("RWS HOLDINGS PLC");
		listaEmpresas.add("RYDER SYSTEM");
		listaEmpresas.add("S&P GLOBAL INC");
		listaEmpresas.add("SACYR");
		listaEmpresas.add("SAFRAN SA");
		listaEmpresas.add("SAGE GROUP PLC");
		listaEmpresas.add("SAINSBURY'S");
		listaEmpresas.add("SAINT GOBAIN");
		listaEmpresas.add("SAINT GOBAIN SA");
		listaEmpresas.add("SAMPO OYJ");
		listaEmpresas.add("SAMSONITE");
		listaEmpresas.add("SANOFI");
		listaEmpresas.add("SANOFI SA");
		listaEmpresas.add("SAP");
		listaEmpresas.add("SAP SE");
		listaEmpresas.add("SAPUTO INC");
		listaEmpresas.add("SARACEN");
		listaEmpresas.add("SAVARIA CORP");
		listaEmpresas.add("SCHLUMBERGER");
		listaEmpresas.add("SCHNEIDER ELECTRIC SE");
		listaEmpresas.add("SCHNITZER STEEL");
		listaEmpresas.add("SCHRODERS PLC");
		listaEmpresas.add("SCOR SE");
		listaEmpresas.add("SCOTTS MIRACLE GRO CO");
		listaEmpresas.add("SEB SA");
		listaEmpresas.add("SEEK");
		listaEmpresas.add("SEI INVESTMENTS CO");
		listaEmpresas.add("SEMPRA ENERGY");
		listaEmpresas.add("SENIOR HOUSING PROPERTIES");
		listaEmpresas.add("SENSIENT TECHNOLOGIES CORP");
		listaEmpresas.add("SES SA");
		listaEmpresas.add("SGS SA");
		listaEmpresas.add("SHENZHEN EXPRESSWAY");
		listaEmpresas.add("SHERWIN WILLIAMS CO");
		listaEmpresas.add("SHIRE PHARMACEUTICALS GROUP PLC");
		listaEmpresas.add("SIEMENS AG");
		listaEmpresas.add("SIEMENS AKTIENGESELLSCHAFT");
		listaEmpresas.add("SILGAN HOLDINGS INC");
		listaEmpresas.add("SILVER WHEATON");
		listaEmpresas.add("SIMCORP A/S");
		listaEmpresas.add("SIMON PROPERTY GROUP INC");
		listaEmpresas.add("SJW CORP");
		listaEmpresas.add("SJW GROUP");
		listaEmpresas.add("SKANDINAVISKA ENSKILDA BANKEN AB CLASS A");
		listaEmpresas.add("SKF");
		listaEmpresas.add("SLATE RETAIL REIT");
		listaEmpresas.add("SMART REAL ESTATE INVESTMENT TRUST");
		listaEmpresas.add("SMITH AO CORP");
		listaEmpresas.add("SMITH NEPHEW");
		listaEmpresas.add("SNIACE");
		listaEmpresas.add("SOCIETE B I C SA");
		listaEmpresas.add("SOCIETE BIC SA");
		listaEmpresas.add("SOCIETE GENERALE SA");
		listaEmpresas.add("SODEXO SA");
		listaEmpresas.add("SOFINA SA");
		listaEmpresas.add("SOFTWARE AG");
		listaEmpresas.add("SOLARIA");
		listaEmpresas.add("SOLVAY SA");
		listaEmpresas.add("SONOCO PRODUCTS CO");
		listaEmpresas.add("SOUTH JERSEY INDUSTRIES");
		listaEmpresas.add("SOUTH JERSEY INDUSTRIES INC");
		listaEmpresas.add("SOUTHERN CO");
		listaEmpresas.add("SOUTHSIDE BANCSHARES");
		listaEmpresas.add("SOUTHWEST GAS CORP");
		listaEmpresas.add("SPECTRIS GROUP PLC");
		listaEmpresas.add("SPIRAX SARCO ENGINEERING PLC");
		listaEmpresas.add("SPIRE INC");
		listaEmpresas.add("SPIRIT AEROSYSTEMS HOLDING");
		listaEmpresas.add("SSE PLC");
		listaEmpresas.add("ST JAMES'S PLACE PLC");
		listaEmpresas.add("STANDARD LIFE ABERDEEN");
		listaEmpresas.add("STANDARD MOTOR PRODUCTS INC");
		listaEmpresas.add("STANLEY BLACK & DECKER");
		listaEmpresas.add("STANLEY BLACK & DECKER INC");
		listaEmpresas.add("STANTEC INC");
		listaEmpresas.add("STARBUCKS CORP");
		listaEmpresas.add("STELLA JONES INC");
		listaEmpresas.add("STEPAN CO");
		listaEmpresas.add("STERICYCLE");
		listaEmpresas.add("STERIS PLC");
		listaEmpresas.add("STOCK YARDS BANCORP INC");
		listaEmpresas.add("STORA ENSO OYJ");
		listaEmpresas.add("STORE CAPITAL CORP");
		listaEmpresas.add("STRYKER CORP");
		listaEmpresas.add("SUEZ");
		listaEmpresas.add("SUEZ SA");
		listaEmpresas.add("SUNCOR");
		listaEmpresas.add("SUNCOR ENERGY INC");
		listaEmpresas.add("SUPREMEX INC");
		listaEmpresas.add("SWISS LIFE HOLDING AG");
		listaEmpresas.add("SWISS PRIME SITE AG");
		listaEmpresas.add("SWISSCOM AG");
		listaEmpresas.add("SYLOGIST LTD");
		listaEmpresas.add("SYSCO CORP");
		listaEmpresas.add("T ROWE PRICE GROUP");
		listaEmpresas.add("T ROWE PRICE GROUP INC");
		listaEmpresas.add("TALGO");
		listaEmpresas.add("TANGER FACTORY OUTLET CENTERS");
		listaEmpresas.add("TANGER FACTORY OUTLET CENTERS INC");
		listaEmpresas.add("TARGET CORP");
		listaEmpresas.add("TATE & LYLE PLC");
		listaEmpresas.add("TATE&LYLE");
		listaEmpresas.add("TAUBMAN CENTERS INC");
		listaEmpresas.add("TECNICAS REUNIDAS");
		listaEmpresas.add("TECSYS INC");
		listaEmpresas.add("TELECOM ITALIA SPA PREFERRED");
		listaEmpresas.add("TELECOM PLUS PLC");
		listaEmpresas.add("TELEFÓNICA");
		listaEmpresas.add("TELEPERFORMANCE SE");
		listaEmpresas.add("TELEPHONE & DATA SYS");
		listaEmpresas.add("TELUS CORP");
		listaEmpresas.add("TEMPLE BAR INVESTMENT TRUST PLC");
		listaEmpresas.add("TENNANT CO");
		listaEmpresas.add("TER BEKE NV");
		listaEmpresas.add("TERNA   RETE ELETTRICA NAZIONALE SPA");
		listaEmpresas.add("TEXAF SA");
		listaEmpresas.add("TEXAS INSTRUMENTS");
		listaEmpresas.add("TEXAS PACIFIC LAND TRUST");
		listaEmpresas.add("TFI INTERNATIONAL INC");
		listaEmpresas.add("THE BANKERS INVESTMENT TRUST PLC");
		listaEmpresas.add("THE BOEING CO");
		listaEmpresas.add("THE CLOROX CO");
		listaEmpresas.add("THE COCA COLA CO");
		listaEmpresas.add("THE HENDERSON SMALLER COMPANIES INVESTMENT TRUST PLC");
		listaEmpresas.add("THE MERCHANTS TRUST PLC");
		listaEmpresas.add("THE SAGE GROUP PLC");
		listaEmpresas.add("THE SHERWIN WILLIAMS CO");
		listaEmpresas.add("THE TRAVELERS COMPANIES INC");
		listaEmpresas.add("THE WALT DISNEY CO");
		listaEmpresas.add("THOMASVILLE BANCSHARES INC");
		listaEmpresas.add("THOMSON REUTERS");
		listaEmpresas.add("THOMSON REUTERS CORP");
		listaEmpresas.add("TIFFANY");
		listaEmpresas.add("TIFFANY & CO");
		listaEmpresas.add("TJX COMPANIES INC");
		listaEmpresas.add("TOMPKINS FINANCIAL CORP");
		listaEmpresas.add("TOOTSIE ROLL INDUSTRIES");
		listaEmpresas.add("TOOTSIE ROLL INDUSTRIES INC");
		listaEmpresas.add("TORO CO");
		listaEmpresas.add("TOROMONT INDUSTRIES LTD");
		listaEmpresas.add("TORONTO DOMINION BANK");
		listaEmpresas.add("TOTAL SA");
		listaEmpresas.add("TP ICAP PLC");
		listaEmpresas.add("TR EUROPEAN GROWTH TRUST PLC");
		listaEmpresas.add("TRACTOR SUPPLY CO");
		listaEmpresas.add("TRANSALTA RENEWABLES INC");
		listaEmpresas.add("TRANSCANADA CORP");
		listaEmpresas.add("TRANSCONTINENTAL INC");
		listaEmpresas.add("TRAVELERS COMPANIES");
		listaEmpresas.add("TRAVELERS COMPANIES INC");
		listaEmpresas.add("TRAVIS PERKINS PLC");
		listaEmpresas.add("TREATT PLC");
		listaEmpresas.add("TUBACEX");
		listaEmpresas.add("TYSON FOODS INC");
		listaEmpresas.add("TÉCNICAS REUNIDAS");
		listaEmpresas.add("UBS GROUP");
		listaEmpresas.add("UGI CORP");
		listaEmpresas.add("ULTRA ELECTRONICS HOLDINGS PLC");
		listaEmpresas.add("UMB FINANCIAL CORP");
		listaEmpresas.add("UMICORE SA");
		listaEmpresas.add("UNDER ARMOUR");
		listaEmpresas.add("UNI SELECT INC");
		listaEmpresas.add("UNIBAIL RODAMCO SE");
		listaEmpresas.add("UNILEVER");
		listaEmpresas.add("UNILEVER NV");
		listaEmpresas.add("UNILEVER NV DUTCH CERTIFICATES");
		listaEmpresas.add("UNION PACIFIC");
		listaEmpresas.add("UNITED BANKSHARES INC");
		listaEmpresas.add("UNITED PARCEL SERVICE");
		listaEmpresas.add("UNITED PARCEL SERVICE INC");
		listaEmpresas.add("UNITED TECHNOLOGIES");
		listaEmpresas.add("UNITED TECHNOLOGIES CORP");
		listaEmpresas.add("UNITED UTILITIES");
		listaEmpresas.add("UNITEDHEALTH GROUP INC");
		listaEmpresas.add("UNIVERSAL CORP");
		listaEmpresas.add("UNIVERSAL HEALTH REALTY TRUST");
		listaEmpresas.add("UNUM GROUP");
		listaEmpresas.add("UPM KYMMENE CORP");
		listaEmpresas.add("UPM KYMMENE OYJ");
		listaEmpresas.add("URSTADT BIDDLE PROPERTIES");
		listaEmpresas.add("US BANCORP");
		listaEmpresas.add("UTAH MEDICAL PRODUCTS INC");
		listaEmpresas.add("VAIL RESORTS");
		listaEmpresas.add("VALEO SA");
		listaEmpresas.add("VALERO ENERGY");
		listaEmpresas.add("VALUE & INCOME TRUST PLC");
		listaEmpresas.add("VECTOR GROUP LTD");
		listaEmpresas.add("VECTREN CORP");
		listaEmpresas.add("VENTAS");
		listaEmpresas.add("VEOLIA");
		listaEmpresas.add("VEOLIA ENVIRONNEMENT SA");
		listaEmpresas.add("VEREIT");
		listaEmpresas.add("VERISIGN");
		listaEmpresas.add("VERIZON COMMUNICATIONS");
		listaEmpresas.add("VERIZON COMMUNICATIONS INC");
		listaEmpresas.add("VF CORP");
		listaEmpresas.add("VICTREX PLC");
		listaEmpresas.add("VIDRALA");
		listaEmpresas.add("VINCI SA");
		listaEmpresas.add("VISA");
		listaEmpresas.add("VISA INC");
		listaEmpresas.add("VISCOFAN");
		listaEmpresas.add("VOCENTO");
		listaEmpresas.add("VODAFONE GROUP PLC");
		listaEmpresas.add("VONOVIA SE");
		listaEmpresas.add("VOPAK NV");
		listaEmpresas.add("VSE CORP");
		listaEmpresas.add("WAL MART INC");
		listaEmpresas.add("WALGREENS BOOTS ALLIANCE INC");
		listaEmpresas.add("WALMART INC");
		listaEmpresas.add("WALT DISNEY CO");
		listaEmpresas.add("WASTE CONNECTIONS INC");
		listaEmpresas.add("WASTE MANAGEMENT");
		listaEmpresas.add("WD 40 CO");
		listaEmpresas.add("WEC ENERGY GROUP INC");
		listaEmpresas.add("WEIR GROUP");
		listaEmpresas.add("WELLS FARGO");
		listaEmpresas.add("WELLTOWER");
		listaEmpresas.add("WENDEL SE");
		listaEmpresas.add("WENDY'S CO");
		listaEmpresas.add("WERELDHAVE BELGIUM VA");
		listaEmpresas.add("WESCO INTERNATIONAL");
		listaEmpresas.add("WEST PHARMACEUTICAL SERVICES");
		listaEmpresas.add("WESTAMERICA BANCORP");
		listaEmpresas.add("WESTLAKE CHEMICAL CORP");
		listaEmpresas.add("WESTROCK CO");
		listaEmpresas.add("WESTWOOD HOLDINGS GROUP INC");
		listaEmpresas.add("WEYCO GROUP INC");
		listaEmpresas.add("WFD UNIBAIL RODAMCO NV");
		listaEmpresas.add("WH SMITH PLC");
		listaEmpresas.add("WHITBREAD");
		listaEmpresas.add("WHITBREAD PLC");
		listaEmpresas.add("WILLIAMS SONOMA INC");
		listaEmpresas.add("WINMARK CORP");
		listaEmpresas.add("WIRECARD AG");
		listaEmpresas.add("WOLTERS KLUWER");
		listaEmpresas.add("WOLTERS KLUWER NV");
		listaEmpresas.add("WP CAREY INC");
		listaEmpresas.add("WPP PLC");
		listaEmpresas.add("WR BERKLEY CORP");
		listaEmpresas.add("WW GRAINGER INC");
		listaEmpresas.add("WYNDHAM DESTINATIONS INC");
		listaEmpresas.add("WYNNSTAY GROUP PLC");
		listaEmpresas.add("XCEL ENERGY");
		listaEmpresas.add("XILINX INC");
		listaEmpresas.add("YORK WATER CO");
		listaEmpresas.add("YOUNG & CO'S BREWERY PLC");
		listaEmpresas.add("ZARDOYA OTIS");
		listaEmpresas.add("ZHEJIANG EXPRESSWAY");
		listaEmpresas.add("ZYTRONIC PLC");
		LISTA_EMPRESAS_GROUP.add(new URLGroup("EMPRESAS", listaEmpresas));
	}

	/**
	 * 
	 */
	private final static Integer MAX_ERROR_RETRY = 2;

	/**
	 * 
	 */
	private final static String URL_INICIAL = "https://www.google.es/search?q=";

	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		try
		{
			run();
		}
		catch (Exception e)
		{
			LOGGER.error("ERROR", e);
		}
		finally
		{
			LOGGER.info("FINALIZADO");
		}
	}

	/**
	 * @throws Exception
	 */
	private static void run() throws Exception
	{
		LOGGER.info("Iniciando driver");
		WebDriver driver = WebDriverBase.getFirefoxWebDriver();
		// WebDriver driver = WebDriverBase.getChromeWebDriver();
		LOGGER.info("Iniciando proceso");
		for (String[] proveedorDatos : LISTA_PROVEEDORES_DATOS)
		{
			for (URLGroup empresasGroup : LISTA_EMPRESAS_GROUP)
			{
				String downloadFolder = empresasGroup.getDownloadFolder();
				LOGGER.info("Procesando grupo [" + downloadFolder + "]");
				List<String> listaEmpresas = empresasGroup.getListaURL();
				int empresaIdx = 0;
				int errorRetry = 0;
				while (empresaIdx < listaEmpresas.size())
				{
					String nombreEmpresa = null;
					try
					{
						nombreEmpresa = listaEmpresas.get(empresaIdx);
						LOGGER.info("Buscando empresa [" + nombreEmpresa + "]");
						if (errorRetry > 0)
						{
							LOGGER.info("Reintento [" + errorRetry + "]");
						}
						// MODO INTRODUCIENDO TEXTO
						// String busquedaURL = URL_INICIAL;
						// LOGGER.info("Cargando URL de búsqueda [" + busquedaURL + "]");
						// driver.get(busquedaURL);
						// new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.tagName("input")));
						// List<WebElement> listaInputs = driver.findElements(By.tagName("input"));
						// for (WebElement input : listaInputs)
						// {
						// String inputTitle = input.getAttribute("title");
						// if (inputTitle != null && inputTitle.indexOf("Buscar") != -1)
						// {
						// input.click();
						// input.clear();
						// input.sendKeys(proveedorDatos[0] + " " + nombreEmpresa);
						// input.sendKeys(Keys.RETURN);
						// }
						// }
						// new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.tagName("a")));
						// List<WebElement> listaLinks = driver.findElements(By.tagName("a"));
						// String resultHrefElemento = null;
						// for (WebElement link : listaLinks)
						// {
						// String linkHref = link.getAttribute("href");
						// if (linkHref != null && linkHref.indexOf(proveedorDatos[1]) != -1)
						// {
						// resultHrefElemento = linkHref;
						// break;
						// }
						// }
						// if (resultHrefElemento == null)
						// {
						// throw new Exception("No se ha encontrado la URL");
						// }
						String busquedaURL = URL_INICIAL + URLEncoder.encode(proveedorDatos[0] + "+" + nombreEmpresa, "UTF-8") + "&nocache=" + System.currentTimeMillis();
						LOGGER.info("Cargando URL de búsqueda [" + busquedaURL + "]");
						driver.get(busquedaURL);
						new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.tagName("a")));
						List<WebElement> listaLinks = driver.findElements(By.tagName("a"));
						String resultHrefElemento = null;
						for (WebElement link : listaLinks)
						{
							String linkHref = link.getAttribute("href");
							if (linkHref != null && linkHref.indexOf(proveedorDatos[1]) != -1)
							{
								resultHrefElemento = linkHref;
								break;
							}
						}
						if (resultHrefElemento == null)
						{
							throw new Exception("No se ha encontrado la URL");
						}
						LOGGER.info(" --- URL Encontrada [" + proveedorDatos[0] + "] [" + downloadFolder + "] [" + nombreEmpresa + "] [" + resultHrefElemento + "]");
						empresaIdx++;
						errorRetry = 0;
						int msEspera = getRandomMsBetween(1000, 4000);
						LOGGER.info("Esperamos [" + String.valueOf(msEspera / 1000) + "] segundos...");
						Thread.sleep(msEspera);
					}
					catch (Exception e)
					{
						LOGGER.error("Se ha producido un error", e);
						errorRetry++;
						if (errorRetry >= MAX_ERROR_RETRY)
						{
							LOGGER.info(" --- URL NO Encontrada [" + proveedorDatos[0] + "] [" + downloadFolder + "] [" + nombreEmpresa + "] [-]");
							empresaIdx++;
							errorRetry = 0;
						}
						LOGGER.info("Esperamos a pulsar ENTER...");
						waitForEnter();
					}
				}
			}
		}
	}

	/**
	 * @param min
	 * @param max
	 * @return
	 */
	private static int getRandomMsBetween(int minMs, int maxMs)
	{
		return RANDOM.nextInt(maxMs - minMs) + minMs;
	}

	/**
	 * 
	 */
	@SuppressWarnings("resource")
	private static void waitForEnter()
	{
		new Scanner(System.in).nextLine();
	}

}
